"""
This type stub file was generated by pyright.
"""

from cssselect2 import SelectorError, compile_selector_list
from tinycss2 import parse_blocks_contents, serialize
from tinycss2.ast import FunctionBlock, IdentToken, LiteralToken, WhitespaceToken
from ... import LOGGER
from ..utils import InvalidValues, remove_whitespace
from .expanders import EXPANDERS
from .properties import PREFIX, PROPRIETARY, UNSTABLE, validate_non_shorthand

"""Validate properties, expanders and descriptors."""
NOT_PRINT_MEDIA = ...
NESTING_SELECTOR = ...
ROOT_TOKEN = ...
def preprocess_declarations(base_url, declarations, prelude=...): # -> Generator[Any | tuple[Any, Any, Any], Any, None]:
    """Expand shorthand properties, filter unsupported properties and values.

    Log a warning for every ignored declaration.

    Return a iterable of ``(name, value, important)`` tuples.

    """
    ...

