"""
This type stub file was generated by pyright.
"""

from ..utils import comma_separated_list, single_keyword, single_token

"""Validate descriptors used for some at-rules."""
DESCRIPTORS = ...
NOT_PRINT_MEDIA = ...
class NoneFakeToken:
    type = ...
    lower_value = ...


class NormalFakeToken:
    type = ...
    lower_value = ...


def preprocess_descriptors(rule, base_url, descriptors): # -> Generator[tuple[Any, Any], Any, None]:
    """Filter unsupported names and values for descriptors.

    Log a warning for every ignored descriptor.

    Return a iterable of ``(name, value)`` tuples.

    """
    ...

def descriptor(rule, descriptor_name=..., wants_base_url=...): # -> Callable[..., Any]:
    """Decorator adding a function to the ``DESCRIPTORS``.

    The name of the descriptor covered by the decorated function is set to
    ``descriptor_name`` if given, or is inferred from the function name
    (replacing underscores by hyphens).

    :param wants_base_url:
        The function takes the stylesheet’s base URL as an additional
        parameter.

    """
    ...

def expand_font_variant(tokens): # -> Generator[tuple[Literal['-alternates', '-caps', '-east-asian', '-numeric', '-position'], list[type[NormalFakeToken]]] | tuple[Literal['-ligatures'], list[type[NormalFakeToken] | type[NoneFakeToken]]] | tuple[str, list[Any]], Any, None]:
    ...

@descriptor('font-face')
def font_family(tokens, allow_spaces=...): # -> LiteralString | None:
    """``font-family`` descriptor validation."""
    ...

@descriptor('font-face', wants_base_url=True)
@comma_separated_list
def src(tokens, base_url): # -> tuple[Literal['local'], Any | LiteralString | None] | tuple[str, str] | tuple[str, Any | str] | None:
    """``src`` descriptor validation."""
    ...

@descriptor('font-face')
@single_keyword
def font_style(keyword): # -> bool:
    """``font-style`` descriptor validation."""
    ...

@descriptor('font-face')
@single_token
def font_weight(token): # -> Literal['normal', 'bold', 100, 200, 300, 400, 500, 600, 700, 800, 900] | None:
    """``font-weight`` descriptor validation."""
    ...

@descriptor('font-face')
@single_keyword
def font_stretch(keyword): # -> bool:
    """``font-stretch`` descriptor validation."""
    ...

@descriptor('font-face')
def font_feature_settings(tokens): # -> tuple[Any, int | Any] | Literal['normal'] | None:
    """``font-feature-settings`` descriptor validation."""
    ...

@descriptor('font-face')
def font_variant(tokens): # -> list[Any] | None:
    """``font-variant`` descriptor validation."""
    ...

@descriptor('font-face')
@comma_separated_list
@single_token
def unicode_range(token): # -> None:
    """``unicode_range`` descriptor validation."""
    ...

@descriptor('counter-style')
def system(tokens): # -> tuple[Literal['extends'], Any, None] | tuple[None, Literal['fixed'], Literal[1]] | tuple[None, Literal['fixed'], Any] | tuple[None, Literal['cyclic', 'numeric', 'alphabetic', 'symbolic', 'additive'], None] | None:
    """``system`` descriptor validation."""
    ...

@descriptor('counter-style', wants_base_url=True)
def negative(tokens, base_url): # -> list[Any] | None:
    """``negative`` descriptor validation."""
    ...

@descriptor('counter-style', 'prefix', wants_base_url=True)
@descriptor('counter-style', 'suffix', wants_base_url=True)
def prefix_suffix(tokens, base_url): # -> tuple[Literal['string'], Any] | tuple[Literal['url'], tuple[str, str] | tuple[str, Any | str]] | None:
    """``prefix`` and ``suffix`` descriptors validation."""
    ...

@descriptor('counter-style')
@comma_separated_list
def range(tokens): # -> tuple[Any, ...] | Literal['auto'] | None:
    """``range`` descriptor validation."""
    ...

@descriptor('counter-style', wants_base_url=True)
def pad(tokens, base_url): # -> tuple[None, ...] | None:
    """``pad`` descriptor validation."""
    ...

@descriptor('counter-style')
@single_token
def fallback(token): # -> None:
    """``fallback`` descriptor validation."""
    ...

@descriptor('counter-style', wants_base_url=True)
def symbols(tokens, base_url): # -> tuple[Any, ...] | None:
    """``symbols`` descriptor validation."""
    ...

@descriptor('counter-style', wants_base_url=True)
def additive_symbols(tokens, base_url): # -> tuple[Any, ...] | None:
    """``additive-symbols`` descriptor validation."""
    ...

