"""
This type stub file was generated by pyright.
"""

from ..utils import Pending

"""Validate properties expanders."""
EXPANDERS = ...
class PendingExpander(Pending):
    """Expander with validation done when defining calculated values."""
    def __init__(self, tokens, validator) -> None:
        ...
    
    def validate(self, tokens, wanted_key):
        ...
    


def expander(property_name): # -> Callable[..., Any]:
    """Decorator adding a function to the ``EXPANDERS``."""
    ...

def generic_expander(*expanded_names, **kwargs): # -> Callable[..., _Wrapped[Callable[..., Any], Any, Callable[..., Any], Generator[tuple[Any | str, Any | PendingProperty | str | PendingExpander], Any, None]]]:
    """Decorator helping expanders to handle ``inherit`` and ``initial``.

    Wrap an expander so that it does not have to handle the 'inherit' and
    'initial' cases, and can just yield name suffixes. Missing suffixes
    get the initial value.

    """
    ...

@expander('border-color')
@expander('border-style')
@expander('border-width')
@expander('margin')
@expander('padding')
@expander('bleed')
def expand_four_sides(tokens, name, base_url): # -> Generator[tuple[Any, PendingExpander] | tuple[Any, Any] | tuple[Any, PendingProperty] | tuple[Any, Any | str], Any, None]:
    """Expand properties setting a token for the four sides of a box."""
    ...

@expander('border-radius')
@generic_expander('border-top-left-radius', 'border-top-right-radius', 'border-bottom-right-radius', 'border-bottom-left-radius', wants_base_url=True)
def border_radius(tokens, name, base_url): # -> Generator[tuple[LiteralString, tuple[Any, Any]], Any, None]:
    """Validator for the ``border-radius`` property."""
    ...

@expander('list-style')
@generic_expander('-type', '-position', '-image', wants_base_url=True)
def expand_list_style(tokens, name, base_url): # -> Generator[tuple[Literal['-image', '-position', '-type'], list[Any]] | tuple[Literal['-type'], list[Any]] | tuple[Literal['-image'], list[Any]], Any, None]:
    """Expand the ``list-style`` shorthand property.

    See https://www.w3.org/TR/CSS21/generate.html#propdef-list-style

    """
    ...

@expander('border')
def expand_border(tokens, name, base_url): # -> Generator[Any, Any, None]:
    """Expand the ``border`` shorthand property.

    See https://www.w3.org/TR/CSS21/box.html#propdef-border

    """
    ...

@expander('border-top')
@expander('border-right')
@expander('border-bottom')
@expander('border-left')
@expander('column-rule')
@expander('outline')
@generic_expander('-width', '-color', '-style')
def expand_border_side(tokens, name): # -> Generator[tuple[Literal['-color', '-width', '-style'], list[Any]], Any, None]:
    """Expand the ``border-*`` shorthand properties.

    See https://www.w3.org/TR/CSS21/box.html#propdef-border-top

    """
    ...

@expander('border-image')
@generic_expander('-outset', '-repeat', '-slice', '-source', '-width', wants_base_url=True)
def expand_border_image(tokens, name, base_url): # -> Generator[tuple[Literal['-source'], list[Any]] | tuple[Literal['-repeat'], list[Any]] | tuple[Literal['-slice'], list[Any]] | tuple[Literal['-width'], list[Any]] | tuple[Literal['-outset'], list[Any]], Any, None]:
    """Expand the ``border-image-*`` shorthand properties.

    See https://drafts.csswg.org/css-backgrounds/#the-border-image

    """
    ...

@expander('mask-border')
@generic_expander('-outset', '-repeat', '-slice', '-source', '-width', '-mode', wants_base_url=True)
def expand_mask_border(tokens, name, base_url): # -> Generator[tuple[Literal['-source'], list[Any]] | tuple[Literal['-mode'], list[Any]] | tuple[Literal['-repeat'], list[Any]] | tuple[Literal['-slice'], list[Any]] | tuple[Literal['-width'], list[Any]] | tuple[Literal['-outset'], list[Any]], Any, None]:
    """Expand the ``mask-border-*`` shorthand properties.

    See https://drafts.fxtf.org/css-masking/#the-mask-border

    """
    ...

@expander('background')
def expand_background(tokens, name, base_url): # -> Generator[tuple[Literal['background-color', 'background-image', 'background-repeat', 'background-attachment', 'background-position', 'background-size', 'background-clip', 'background-origin'], Literal['initial', 'inherit']] | tuple[str, PendingExpander] | tuple[Any, list[Any]] | tuple[Literal['background-color'], Any], Any, None]:
    """Expand the ``background`` shorthand property.

    See https://drafts.csswg.org/css-backgrounds-3/#the-background

    """
    ...

@expander('text-decoration')
@generic_expander('-line', '-color', '-style', '-thickness')
def expand_text_decoration(tokens, name): # -> Generator[tuple[Literal['-line'], list[Any]] | tuple[Literal['-color'], list[Any]] | tuple[Literal['-style'], list[Any]] | tuple[Literal['-thickness'], list[Any]], Any, None]:
    """Expand the ``text-decoration`` shorthand property."""
    ...

def expand_page_break_before_after(tokens, name): # -> Generator[tuple[Any, Any] | tuple[Any, list[IdentToken]], Any, None]:
    """Expand legacy ``page-break-before`` and ``page-break-after`` properties.

    See https://www.w3.org/TR/css-break-3/#page-break-properties

    """
    ...

@expander('page-break-after')
@generic_expander('break-after')
def expand_page_break_after(tokens, name): # -> Generator[tuple[Any, Any] | tuple[Any, list[IdentToken]], Any, None]:
    """Expand legacy ``page-break-after`` property.

    See https://www.w3.org/TR/css-break-3/#page-break-properties

    """
    ...

@expander('page-break-before')
@generic_expander('break-before')
def expand_page_break_before(tokens, name): # -> Generator[tuple[Any, Any] | tuple[Any, list[IdentToken]], Any, None]:
    """Expand legacy ``page-break-before`` property.

    See https://www.w3.org/TR/css-break-3/#page-break-properties

    """
    ...

@expander('page-break-inside')
@generic_expander('break-inside')
def expand_page_break_inside(tokens, name): # -> Generator[tuple[Literal['break-inside'], Any], Any, None]:
    """Expand the legacy ``page-break-inside`` property.

    See https://www.w3.org/TR/css-break-3/#page-break-properties

    """
    ...

@expander('columns')
@generic_expander('column-width', 'column-count')
def expand_columns(tokens, name): # -> Generator[tuple[Literal['column-width', 'column-count'], list[Any]] | tuple[Literal['column-width', 'column-count'], list[IdentToken]], Any, None]:
    """Expand the ``columns`` shorthand property."""
    ...

@expander('font-variant')
@generic_expander('-alternates', '-caps', '-east-asian', '-ligatures', '-numeric', '-position')
def font_variant(tokens, name): # -> Generator[tuple[Literal['-alternates', '-caps', '-east-asian', '-numeric', '-position'], list[type[NormalFakeToken]]] | tuple[Literal['-ligatures'], list[type[NormalFakeToken] | type[NoneFakeToken]]] | tuple[str, list[Any]], Any, None]:
    """Expand the ``font-variant`` shorthand property.

    https://www.w3.org/TR/css-fonts-3/#font-variant-prop

    """
    ...

@expander('font')
@generic_expander('-style', '-variant-caps', '-weight', '-stretch', '-size', 'line-height', '-family')
def expand_font(tokens, name): # -> Generator[tuple[Literal['-style', '-variant-caps', '-weight', '-stretch'], list[Any]] | tuple[Literal['-size'], list[Any]] | tuple[Literal['line-height'], list[Any]] | tuple[Literal['-family'], list[Any]], Any, None]:
    """Expand the ``font`` shorthand property.

    https://www.w3.org/TR/css-fonts-3/#font-prop

    """
    ...

@expander('word-wrap')
@generic_expander('overflow-wrap')
def expand_word_wrap(tokens, name): # -> Generator[tuple[Literal['overflow-wrap'], Any], Any, None]:
    """Expand the ``word-wrap`` legacy property.

    See https://www.w3.org/TR/css-text-3/#overflow-wrap

    """
    ...

@expander('flex')
@generic_expander('-grow', '-shrink', '-basis')
def expand_flex(tokens, name): # -> Generator[tuple[Literal['-grow'], list[NumberToken]] | tuple[Literal['-shrink'], list[NumberToken]] | tuple[Literal['-basis'], list[IdentToken]] | tuple[Literal['-basis'], list[DimensionToken | Any | None]], Any, None]:
    """Expand the ``flex`` property."""
    ...

@expander('flex-flow')
@generic_expander('flex-direction', 'flex-wrap')
def expand_flex_flow(tokens, name): # -> Generator[tuple[Literal['flex-direction'], list[Any]] | tuple[Literal['flex-wrap'], list[Any]], Any, None]:
    """Expand the ``flex-flow`` property."""
    ...

@expander('grid-template')
@generic_expander('-columns', '-rows', '-areas')
def expand_grid_template(tokens, name): # -> Generator[tuple[Literal['-columns'], list[IdentToken]] | tuple[Literal['-rows'], list[IdentToken]] | tuple[Literal['-areas'], list[IdentToken]] | tuple[Literal['-columns'], list[Any]] | tuple[Literal['-rows'], list[Any]], Any, None]:
    """Expand the ``grid-template`` property."""
    ...

@expander('grid')
@generic_expander('-template-columns', '-template-rows', '-template-areas', '-auto-columns', '-auto-rows', '-auto-flow')
def expand_grid(tokens, name): # -> Generator[tuple[LiteralString, list[IdentToken]] | tuple[Literal['-auto-columns'], list[IdentToken]] | tuple[Literal['-auto-rows'], list[IdentToken]] | tuple[Literal['-auto-flow'], list[IdentToken]] | tuple[Literal['-auto-flow'], tuple[IdentToken, Any] | tuple[IdentToken]] | tuple[str, tuple[Any, ...]] | tuple[str, list[IdentToken]] | tuple[LiteralString, tuple[Any, ...]] | tuple[Literal['-template-areas'], list[IdentToken]], Any, None]:
    """Expand the ``grid`` property."""
    ...

@expander('grid-column')
@expander('grid-row')
@generic_expander('-start', '-end')
def expand_grid_column_row(tokens, name): # -> Generator[tuple[LiteralString, tuple[Any, ...] | tuple[IdentToken]], Any, None]:
    """Expand the ``grid-[column|row]`` properties."""
    ...

@expander('grid-area')
@generic_expander('grid-row-start', 'grid-row-end', 'grid-column-start', 'grid-column-end')
def expand_grid_area(tokens, name): # -> Generator[tuple[LiteralString, tuple[Any, ...] | tuple[IdentToken]], Any, None]:
    """Expand the ``grid-area`` property."""
    ...

@expander('grid-gap')
@expander('gap')
@generic_expander('column-gap', 'row-gap')
def expand_gap(tokens, name): # -> Generator[tuple[Literal['row-gap'], Any] | tuple[Literal['column-gap'], Any], Any, None]:
    """Expand the ``gap`` property."""
    ...

@expander('grid-column-gap')
@generic_expander('column-gap')
def expand_legacy_column_gap(tokens, name): # -> Generator[tuple[Literal['column-gap'], Any], Any, None]:
    """Expand legacy ``grid-column-gap`` property."""
    ...

@expander('grid-row-gap')
@generic_expander('row-gap')
def expand_legacy_row_gap(tokens, name): # -> Generator[tuple[Literal['row-gap'], Any], Any, None]:
    """Expand legacy ``grid-row-gap`` property."""
    ...

@expander('place-content')
@generic_expander('align-content', 'justify-content')
def expand_place_content(tokens, name):
    """Expand the ``place-content`` property."""
    ...

@expander('place-items')
@generic_expander('align-items', 'justify-items')
def expand_place_items(tokens, name):
    """Expand the ``place-items`` property."""
    ...

@expander('place-self')
@generic_expander('align-self', 'justify-self')
def expand_place_self(tokens, name):
    """Expand the ``place-self`` property."""
    ...

@expander('line-clamp')
@generic_expander('max-lines', 'continue', 'block-ellipsis')
def expand_line_clamp(tokens, name): # -> Generator[tuple[Literal['max-lines'], list[IdentToken]] | tuple[Literal['continue'], list[IdentToken]] | tuple[Literal['block-ellipsis'], list[IdentToken]] | tuple[Literal['max-lines'], list[Any]] | tuple[Literal['block-ellipsis'], list[Any]], Any, None]:
    """Expand the ``line-clamp`` property."""
    ...

@expander('text-align')
@generic_expander('-all', '-last')
def expand_text_align(tokens, name): # -> Generator[tuple[Literal['-all'], list[IdentToken | Any]] | tuple[Literal['-last'], list[IdentToken | Any]], Any, None]:
    """Expand the ``text-align`` property."""
    ...

