"""
This type stub file was generated by pyright.
"""

from ..utils import Pending, comma_separated_list, single_keyword, single_token

"""Validate properties.

See https://www.w3.org/TR/CSS21/propidx.html and various CSS3 modules.

"""
PREFIX = ...
PROPRIETARY = ...
UNSTABLE = ...
PROPERTIES = ...
class PendingProperty(Pending):
    """Property with validation done when defining calculated values."""
    def validate(self, tokens, wanted_key): # -> PendingProperty | str:
        ...
    


def property(property_name=..., proprietary=..., unstable=..., wants_base_url=...): # -> Callable[..., Any]:
    """Decorator adding a function to the ``PROPERTIES``.

    The name of the property covered by the decorated function is set to
    ``property_name`` if given, or is inferred from the function name
    (replacing underscores by hyphens).

    :param proprietary:
        Proprietary (vendor-specific, non-standard) are prefixed: anchors can
        for example be set using ``-weasy-anchor: attr(id)``.
        See https://www.w3.org/TR/CSS/#proprietary
    :param unstable:
        Mark properties that are defined in specifications that didn't reach
        the Candidate Recommandation stage. They can be used both
        vendor-prefixed or unprefixed.
        See https://www.w3.org/TR/CSS/#unstable-syntax
    :param wants_base_url:
        The function takes the stylesheet’s base URL as an additional
        parameter.

    """
    ...

def validate_non_shorthand(tokens, name, base_url=..., required=...): # -> tuple[tuple[Any, Any]] | tuple[tuple[Any, PendingProperty]] | tuple[tuple[Any, Any | str]]:
    """Validator for non-shorthand properties."""
    ...

@property()
@comma_separated_list
@single_keyword
def background_attachment(keyword): # -> bool:
    """``background-attachment`` property validation."""
    ...

@property('background-color')
@property('border-top-color')
@property('border-right-color')
@property('border-bottom-color')
@property('border-left-color')
@property('column-rule-color', unstable=True)
@property('text-decoration-color')
@single_token
def other_colors(token): # -> Color | Literal['currentcolor'] | None:
    ...

@property()
@single_token
def outline_color(token): # -> Color | Literal['currentcolor'] | None:
    ...

@property()
@single_keyword
def border_collapse(keyword): # -> bool:
    ...

@property()
@single_keyword
def empty_cells(keyword): # -> bool:
    """``empty-cells`` property validation."""
    ...

@property('color')
@single_token
def color(token): # -> Color | Literal['inherit'] | None:
    """``*-color`` and ``color`` properties validation."""
    ...

@property('background-image', wants_base_url=True)
@comma_separated_list
@single_token
def background_image(token, base_url): # -> tuple[Literal['none'], None] | tuple[Literal['url'], str | Any] | tuple[Literal['linear-gradient'], LinearGradient] | tuple[Literal['radial-gradient'], RadialGradient] | None:
    ...

@property('list-style-image', wants_base_url=True)
@single_token
def list_style_image(token, base_url): # -> tuple[Literal['none'], None] | tuple[Literal['url'], str | Any] | None:
    """``list-style-image`` property validation."""
    ...

@property()
def transform_origin(tokens): # -> tuple[Dimension, Dimension] | None:
    """``transform-origin`` property validation."""
    ...

@property()
@comma_separated_list
def background_position(tokens): # -> tuple[Literal['left'], Dimension, Literal['top'], Dimension] | tuple[Literal['left', 'right'], Dimension, Literal['top', 'bottom'], Dimension] | tuple[Literal['left'], Dimension, Literal['top', 'bottom'], Dimension] | tuple[Literal['left', 'right'], Dimension, Literal['top'], Dimension] | None:
    """``background-position`` property validation."""
    ...

@property()
@comma_separated_list
def object_position(tokens): # -> tuple[Literal['left'], Dimension, Literal['top'], Dimension] | tuple[Literal['left', 'right'], Dimension, Literal['top', 'bottom'], Dimension] | tuple[Literal['left'], Dimension, Literal['top', 'bottom'], Dimension] | tuple[Literal['left', 'right'], Dimension, Literal['top'], Dimension] | None:
    """``object-position`` property validation."""
    ...

@property()
@comma_separated_list
def background_repeat(tokens): # -> tuple[Literal['repeat'], Literal['no-repeat']] | tuple[Literal['no-repeat'], Literal['repeat']] | tuple[Any | None, ...] | tuple[Any | None, Any | None] | None:
    """``background-repeat`` property validation."""
    ...

@property()
@comma_separated_list
def background_size(tokens): # -> tuple[Literal['auto'], Literal['auto']] | tuple[Dimension, Literal['auto']] | tuple[Any, ...] | Literal['contain', 'cover'] | None:
    """Validation for ``background-size``."""
    ...

@property('background-clip')
@property('background-origin')
@comma_separated_list
@single_keyword
def box(keyword): # -> bool:
    """Validation for the ``<box>`` type used in ``background-clip``
    and ``background-origin``."""
    ...

@property()
def border_spacing(tokens): # -> tuple[Dimension | None, Dimension | None] | tuple[Dimension | None, ...] | None:
    """Validator for the `border-spacing` property."""
    ...

@property('border-top-right-radius')
@property('border-bottom-right-radius')
@property('border-bottom-left-radius')
@property('border-top-left-radius')
def border_corner_radius(tokens): # -> tuple[Dimension | None, Dimension | None] | tuple[Dimension | None, ...] | None:
    """Validator for the `border-*-radius` properties."""
    ...

@property('border-top-style')
@property('border-right-style')
@property('border-left-style')
@property('border-bottom-style')
@property('column-rule-style', unstable=True)
@single_keyword
def border_style(keyword): # -> bool:
    """``border-*-style`` properties validation."""
    ...

@property('break-before')
@property('break-after')
@single_keyword
def break_before_after(keyword): # -> bool:
    """``break-before`` and ``break-after`` properties validation."""
    ...

@property()
@single_keyword
def break_inside(keyword): # -> bool:
    """``break-inside`` property validation."""
    ...

@property()
@single_keyword
def box_decoration_break(keyword): # -> bool:
    """``box-decoration-break`` property validation."""
    ...

@property()
@single_token
def block_ellipsis(token): # -> tuple[Literal['string'], Any] | Literal['none', 'auto'] | None:
    """``box-ellipsis`` property validation."""
    ...

@property('continue', unstable=True)
@single_keyword
def continue_(keyword): # -> bool:
    """``continue`` property validation."""
    ...

@property(unstable=True)
@single_token
def max_lines(token): # -> Literal['none'] | None:
    ...

@property(unstable=True)
@single_keyword
def margin_break(keyword): # -> bool:
    """``margin-break`` property validation."""
    ...

@property(unstable=True)
@single_token
def page(token): # -> Literal['auto'] | None:
    """``page`` property validation."""
    ...

@property('bleed-left', unstable=True)
@property('bleed-right', unstable=True)
@property('bleed-top', unstable=True)
@property('bleed-bottom', unstable=True)
@single_token
def bleed(token): # -> Dimension | Literal['auto'] | None:
    """``bleed`` property validation."""
    ...

@property(unstable=True)
def marks(tokens): # -> tuple[Any | None, ...] | tuple[Literal['crop', 'cross']] | tuple[()] | None:
    """``marks`` property validation."""
    ...

@property('outline-style')
@single_keyword
def outline_style(keyword): # -> bool:
    """``outline-style`` properties validation."""
    ...

@property('border-top-width')
@property('border-right-width')
@property('border-left-width')
@property('border-bottom-width')
@property('column-rule-width', unstable=True)
@property('outline-width')
@single_token
def border_width(token): # -> Dimension | Literal['thin', 'medium', 'thick'] | None:
    """Border, column rule and outline widths properties validation."""
    ...

@property('border-image-source', wants_base_url=True)
@property('mask-border-source', wants_base_url=True)
@single_token
def border_image_source(token, base_url): # -> tuple[Literal['none'], None] | tuple[Literal['url'], str | Any] | tuple[Literal['linear-gradient'], LinearGradient] | tuple[Literal['radial-gradient'], RadialGradient] | None:
    ...

@property('border-image-slice')
@property('mask-border-slice')
def border_image_slice(tokens): # -> tuple[Any, ...] | None:
    ...

@property('border-image-width')
@property('mask-border-width')
def border_image_width(tokens): # -> tuple[Any, ...] | None:
    ...

@property('border-image-outset')
@property('mask-border-outset')
def border_image_outset(tokens): # -> tuple[Any, ...] | None:
    ...

@property('border-image-repeat')
@property('mask-border-repeat')
def border_image_repeat(tokens): # -> tuple[Any | None, ...] | None:
    ...

@property()
@single_keyword
def mask_border_mode(keyword): # -> bool:
    ...

@property(unstable=True)
@single_token
def column_width(token): # -> Dimension | Literal['auto'] | None:
    """``column-width`` property validation."""
    ...

@property(unstable=True)
@single_keyword
def column_span(keyword): # -> bool:
    """``column-span`` property validation."""
    ...

@property()
@single_keyword
def box_sizing(keyword): # -> bool:
    """Validation for the ``box-sizing`` property from css3-ui"""
    ...

@property()
@single_keyword
def caption_side(keyword): # -> bool:
    """``caption-side`` properties validation."""
    ...

@property()
@single_keyword
def clear(keyword): # -> bool:
    """``clear`` property validation."""
    ...

@property()
@single_token
def clip(token): # -> tuple[Any, ...] | tuple[()] | None:
    """Validation for the ``clip`` property."""
    ...

@property(wants_base_url=True)
def content(tokens, base_url): # -> tuple[Literal['normal', 'none']] | list[tuple[Literal['string'], Any] | tuple[Literal['attr()'], tuple[Any, Any | str, Any | str]] | tuple[LiteralString, tuple[Any, ...]] | tuple[Literal['content()'], Literal['text']] | tuple[Literal['content()'], Literal['text', 'before', 'after', 'first-letter', 'marker']] | tuple[str, tuple[Any, str]] | tuple[Literal['url'], tuple[str, str]] | tuple[Literal['url'], tuple[str, Any | str]] | tuple[Literal['quote'], Literal['open-quote', 'close-quote', 'no-open-quote', 'no-close-quote']] | tuple[Literal['leader()'], tuple[str, Any | str | None]] | None] | None:
    """``content`` property validation."""
    ...

@property()
def counter_increment(tokens): # -> tuple[()] | tuple[Any, ...] | None:
    """``counter-increment`` property validation."""
    ...

@property()
def counter_reset(tokens): # -> tuple[()] | tuple[Any, ...] | None:
    """``counter-reset`` property validation."""
    ...

@property()
def counter_set(tokens): # -> tuple[()] | tuple[Any, ...] | None:
    """``counter-set`` property validation."""
    ...

def counter(tokens, default_integer): # -> tuple[()] | tuple[Any, ...] | None:
    """``counter-increment`` and ``counter-reset`` properties validation."""
    ...

@property('top')
@property('right')
@property('left')
@property('bottom')
@property('margin-top')
@property('margin-right')
@property('margin-bottom')
@property('margin-left')
@property('text-underline-offset')
@single_token
def lenght_precentage_or_auto(token): # -> Dimension | Literal['auto'] | None:
    """``margin-*`` and various other properties validation."""
    ...

@property('height')
@property('width')
@single_token
def width_height(token): # -> Dimension | Literal['auto'] | None:
    """Validation for the ``width`` and ``height`` properties."""
    ...

@property('column-gap', unstable=True)
@property('row-gap', unstable=True)
@single_token
def gap(token): # -> Dimension | Literal['normal'] | None:
    """Validation for the ``column-gap`` and ``row-gap`` properties."""
    ...

@property(unstable=True)
@single_keyword
def column_fill(keyword): # -> bool:
    """``column-fill`` property validation."""
    ...

@property()
@single_keyword
def direction(keyword): # -> bool:
    """``direction`` property validation."""
    ...

@property()
def display(tokens): # -> tuple[Literal['none', 'table-caption', 'table-row-group', 'table-cell', 'table-header-group', 'table-footer-group', 'table-row', 'table-column-group', 'table-column']] | tuple[LiteralString, ...] | tuple[Literal['inline'], Literal['flow-root']] | tuple[Literal['block', 'inline'], Literal['flow', 'flow-root'], Literal['list-item']] | tuple[Literal['block', 'inline'], Literal['flow', 'flow-root', 'table', 'flex', 'grid']] | None:
    """``display`` property validation."""
    ...

@property('float')
@single_keyword
def float_(keyword): # -> bool:
    """``float`` property validation."""
    ...

@property()
@comma_separated_list
def font_family(tokens): # -> LiteralString | None:
    """``font-family`` property validation."""
    ...

@property()
@single_keyword
def font_kerning(keyword): # -> bool:
    ...

@property()
@single_token
def font_language_override(token): # -> Literal['normal'] | None:
    ...

@property()
def font_variant_ligatures(tokens): # -> tuple[Any, ...] | Literal['normal', 'none'] | None:
    ...

@property()
@single_keyword
def font_variant_position(keyword): # -> bool:
    ...

@property()
@single_keyword
def font_variant_caps(keyword): # -> bool:
    ...

@property()
def font_variant_numeric(tokens): # -> tuple[Any, ...] | Literal['normal'] | None:
    ...

@property()
def font_feature_settings(tokens): # -> tuple[Any, int | Any] | Literal['normal'] | None:
    """``font-feature-settings`` property validation."""
    ...

@property()
@single_keyword
def font_variant_alternates(keyword): # -> bool:
    ...

@property()
def font_variant_east_asian(tokens): # -> tuple[Any, ...] | Literal['normal'] | None:
    ...

@property()
def font_variation_settings(tokens): # -> tuple[Any, Any] | Literal['normal'] | None:
    """``font-variation-settings`` property validation."""
    ...

@property()
@single_token
def font_size(token): # -> Dimension | Literal['smaller', 'larger'] | None:
    """``font-size`` property validation."""
    ...

@property()
@single_keyword
def font_style(keyword): # -> bool:
    """``font-style`` property validation."""
    ...

@property()
@single_keyword
def font_stretch(keyword): # -> bool:
    """Validation for the ``font-stretch`` property."""
    ...

@property()
@single_token
def font_weight(token): # -> Literal['normal', 'bold', 'bolder', 'lighter', 100, 200, 300, 400, 500, 600, 700, 800, 900] | None:
    """``font-weight`` property validation."""
    ...

@property()
@single_keyword
def object_fit(keyword): # -> bool:
    ...

@property(unstable=True)
@single_token
def image_resolution(token): # -> None:
    ...

@property('letter-spacing')
@property('word-spacing')
@single_token
def spacing(token): # -> Dimension | Literal['normal'] | None:
    """Validation for ``letter-spacing`` and ``word-spacing``."""
    ...

@property()
@single_token
def outline_offset(token): # -> Dimension | None:
    """Validation for ``outline-offset``."""
    ...

@property()
@single_token
def line_height(token): # -> Dimension | Literal['normal'] | None:
    """``line-height`` property validation."""
    ...

@property()
@single_keyword
def list_style_position(keyword): # -> bool:
    """``list-style-position`` property validation."""
    ...

@property()
@single_token
def list_style_type(token): # -> tuple[Literal['string'], Any] | tuple[Literal['symbols()'], tuple[Any, ...]] | None:
    """``list-style-type`` property validation."""
    ...

@property('min-width')
@property('min-height')
@single_token
def min_width_height(token): # -> Dimension | Literal['auto'] | None:
    """``min-width`` and ``min-height`` properties validation."""
    ...

@property('padding-top')
@property('padding-right')
@property('padding-bottom')
@property('padding-left')
@single_token
def length_or_precentage(token): # -> Dimension | None:
    """``padding-*`` properties validation."""
    ...

@property('max-width')
@property('max-height')
@single_token
def max_width_height(token): # -> Dimension | None:
    """Validation for max-width and max-height"""
    ...

@property()
@single_token
def opacity(token): # -> int | None:
    """Validation for the ``opacity`` property."""
    ...

@property()
@single_token
def z_index(token): # -> Literal['auto'] | None:
    """Validation for the ``z-index`` property."""
    ...

@property('orphans')
@property('widows')
@single_token
def orphans_widows(token): # -> None:
    """Validation for the ``orphans`` and ``widows`` properties."""
    ...

@property(unstable=True)
@single_token
def column_count(token): # -> Literal['auto'] | None:
    """Validation for the ``column-count`` property."""
    ...

@property()
@single_keyword
def overflow(keyword): # -> bool:
    """Validation for the ``overflow`` property."""
    ...

@property()
@single_keyword
def text_overflow(keyword): # -> bool:
    """Validation for the ``text-overflow`` property."""
    ...

@property()
@single_token
def position(token): # -> tuple[Literal['running()'], Any] | Literal['static', 'relative', 'absolute', 'fixed'] | None:
    """``position`` property validation."""
    ...

@property()
def quotes(tokens): # -> tuple[tuple[Any, ...], tuple[Any, ...]] | Literal['auto', 'none'] | None:
    """``quotes`` property validation."""
    ...

@property()
@single_keyword
def table_layout(keyword): # -> Literal['fixed', 'auto'] | None:
    """Validation for the ``table-layout`` property"""
    ...

@property()
@single_keyword
def text_align_all(keyword): # -> bool:
    """``text-align-all`` property validation."""
    ...

@property()
@single_keyword
def text_align_last(keyword): # -> bool:
    """``text-align-last`` property validation."""
    ...

@property()
def text_decoration_line(tokens): # -> set[Any | None] | Literal['none'] | None:
    """``text-decoration-line`` property validation."""
    ...

@property()
@single_keyword
def text_decoration_style(keyword): # -> Literal['solid', 'double', 'dotted', 'dashed', 'wavy'] | None:
    """``text-decoration-style`` property validation."""
    ...

@property()
@single_token
def text_decoration_thickness(token): # -> Dimension | Literal[True] | None:
    """``text-decoration-thickness`` property validation."""
    ...

@property()
@single_token
def text_indent(token): # -> Dimension | None:
    """``text-indent`` property validation."""
    ...

@property()
@single_keyword
def text_transform(keyword): # -> bool:
    """``text-align`` property validation."""
    ...

@property()
@single_token
def vertical_align(token): # -> Dimension | Literal['baseline', 'middle', 'sub', 'super', 'text-top', 'text-bottom', 'top', 'bottom'] | None:
    """Validation for the ``vertical-align`` property"""
    ...

@property()
@single_keyword
def visibility(keyword): # -> bool:
    """``white-space`` property validation."""
    ...

@property()
@single_keyword
def white_space(keyword): # -> bool:
    """``white-space`` property validation."""
    ...

@property()
@single_keyword
def overflow_wrap(keyword): # -> bool:
    """``overflow-wrap`` property validation."""
    ...

@property()
@single_keyword
def word_break(keyword): # -> bool:
    """``word-break`` property validation."""
    ...

@property()
@single_token
def flex_basis(token): # -> Dimension | Literal['auto', 'content'] | None:
    """``flex-basis`` property validation."""
    ...

@property()
@single_keyword
def flex_direction(keyword): # -> bool:
    """``flex-direction`` property validation."""
    ...

@property('flex-grow')
@property('flex-shrink')
@single_token
def flex_grow_shrink(token): # -> None:
    ...

@property('grid-auto-columns')
@property('grid-auto-rows')
def grid_auto(tokens): # -> tuple[Any, ...] | None:
    """``grid-auto-columns`` and ``grid-auto-rows`` properties validation."""
    ...

@property()
def grid_auto_flow(tokens): # -> tuple[Literal['row', 'column']] | tuple[Literal['dense'], Literal['row']] | tuple[Any | None, ...] | None:
    """``grid-auto-flow`` property validation."""
    ...

@property('grid-template-columns')
@property('grid-template-rows')
def grid_template(tokens): # -> tuple[Any, ...] | Literal['none'] | None:
    """``grid-template-columns`` and ``grid-template-rows`` validation."""
    ...

@property()
def grid_template_areas(tokens): # -> tuple[Any, ...] | Literal['none'] | None:
    """``grid-template-areas`` property validation."""
    ...

@property('grid-row-start')
@property('grid-row-end')
@property('grid-column-start')
@property('grid-column-end')
def grid_line(tokens): # -> tuple[None, None, Any] | tuple[None, Any, None] | tuple[Literal['span'], Any | None, Any | None] | tuple[None, Any, Any | None] | Literal['auto'] | None:
    """``grid-[row|column]-[start—end]`` properties validation."""
    ...

@property()
@single_keyword
def flex_wrap(keyword): # -> bool:
    """``flex-wrap`` property validation."""
    ...

@property()
def justify_content(tokens): # -> tuple[Literal['center', 'space-between', 'space-around', 'space-evenly', 'stretch', 'normal', 'flex-start', 'flex-end', 'start', 'end', 'left', 'right']] | tuple[Any | None, ...] | None:
    """``justify-content`` property validation."""
    ...

@property()
def justify_items(tokens): # -> tuple[Literal['normal', 'stretch', 'center', 'start', 'end', 'self-start', 'self-end', 'flex-start', 'flex-end', 'left', 'right', 'legacy']] | tuple[Literal['first'], Literal['baseline']] | tuple[Any | None, ...] | None:
    """``justify-items`` property validation."""
    ...

@property()
def justify_self(tokens): # -> tuple[Literal['auto', 'normal', 'stretch', 'center', 'start', 'end', 'self-start', 'self-end', 'flex-start', 'flex-end', 'left', 'right']] | tuple[Literal['first'], Literal['baseline']] | tuple[Any | None, ...] | None:
    """``justify-self`` property validation."""
    ...

@property()
def align_items(tokens): # -> tuple[Literal['normal', 'stretch', 'center', 'start', 'end', 'self-start', 'self-end', 'flex-start', 'flex-end']] | tuple[Literal['first'], Literal['baseline']] | tuple[Any | None, ...] | None:
    """``align-items`` property validation."""
    ...

@property()
def align_self(tokens): # -> tuple[Literal['auto', 'normal', 'stretch', 'center', 'start', 'end', 'self-start', 'self-end', 'flex-start', 'flex-end']] | tuple[Literal['first'], Literal['baseline']] | tuple[Any | None, ...] | None:
    """``align-self`` property validation."""
    ...

@property()
def align_content(tokens): # -> tuple[Literal['center', 'space-between', 'space-around', 'space-evenly', 'stretch', 'normal', 'flex-start', 'flex-end', 'start', 'end']] | tuple[Literal['first'], Literal['baseline']] | tuple[Any | None, ...] | None:
    """``align-content`` property validation."""
    ...

@property()
@single_token
def order(token): # -> None:
    ...

@property(unstable=True)
@single_keyword
def image_rendering(keyword): # -> bool:
    """Validation for ``image-rendering``."""
    ...

@property(unstable=True)
def image_orientation(tokens): # -> tuple[Any | Literal[0], bool] | Literal['none', 'from-image'] | None:
    """Validation for ``image-orientation``."""
    ...

@property(unstable=True)
def size(tokens): # -> tuple[Dimension | None, Dimension | None] | tuple[Dimension | None, ...] | tuple[Dimension, Dimension] | tuple[Dimension, ...] | None:
    """``size`` property validation.

    See https://www.w3.org/TR/css-page-3/#page-size-prop

    """
    ...

@property(proprietary=True)
@single_token
def anchor(token): # -> tuple[Literal['attr()'], Any] | Literal['none'] | None:
    """Validation for ``anchor``."""
    ...

@property(proprietary=True, wants_base_url=True)
@single_token
def link(token, base_url): # -> tuple[Literal['url'], tuple[str, str]] | tuple[Literal['url'], tuple[str, Any | str]] | tuple[Literal['attr()'], tuple[Any, Any | str, Any | str]] | tuple[Literal['attr()'], Any] | Literal['none'] | None:
    """Validation for ``link``."""
    ...

@property()
@single_token
def tab_size(token): # -> Dimension | None:
    """Validation for ``tab-size``.

    See https://www.w3.org/TR/css-text-3/#tab-size

    """
    ...

@property(unstable=True)
@single_token
def hyphens(token): # -> Literal['none', 'manual', 'auto'] | None:
    """Validation for ``hyphens``."""
    ...

@property(unstable=True)
@single_token
def hyphenate_character(token): # -> Literal['‐'] | None:
    """Validation for ``hyphenate-character``."""
    ...

@property(unstable=True)
@single_token
def hyphenate_limit_zone(token): # -> Dimension | None:
    """Validation for ``hyphenate-limit-zone``."""
    ...

@property(unstable=True)
def hyphenate_limit_chars(tokens): # -> tuple[Literal[5], Literal[2], Literal[2]] | tuple[Any, Literal[2], Literal[2]] | tuple[Any, Any, Any] | tuple[Literal[5], Any, Any] | tuple[Any | Literal[5], Any | Literal[2], Any | Literal[2]] | None:
    """Validation for ``hyphenate-limit-chars``."""
    ...

@property(proprietary=True)
@single_token
def lang(token): # -> tuple[Literal['attr()'], Any] | tuple[Literal['string'], Any] | Literal['none'] | None:
    """Validation for ``lang``."""
    ...

@property(unstable=True, wants_base_url=True)
def bookmark_label(tokens, base_url): # -> tuple[tuple[Literal['string'], Any] | tuple[Literal['attr()'], tuple[Any, Any | str, Any | str]] | tuple[LiteralString, tuple[Any, ...]] | tuple[Literal['content()'], Literal['text']] | tuple[Literal['content()'], Literal['text', 'before', 'after', 'first-letter', 'marker']] | tuple[str, tuple[Any, str]] | tuple[Literal['url'], tuple[str, str]] | tuple[Literal['url'], tuple[str, Any | str]] | tuple[Literal['quote'], Literal['open-quote', 'close-quote', 'no-open-quote', 'no-close-quote']] | tuple[Literal['leader()'], tuple[str, Any | str | None]] | None, ...] | None:
    """Validation for ``bookmark-label``."""
    ...

@property(unstable=True)
@single_token
def bookmark_level(token): # -> Literal['none'] | None:
    """Validation for ``bookmark-level``."""
    ...

@property(unstable=True)
@single_keyword
def bookmark_state(keyword): # -> bool:
    """Validation for ``bookmark-state``."""
    ...

@property(unstable=True)
@single_keyword
def footnote_display(keyword): # -> bool:
    """Validation for ``footnote-display``."""
    ...

@property(unstable=True)
@single_keyword
def footnote_policy(keyword): # -> bool:
    """Validation for ``footnote-policy``."""
    ...

@property(unstable=True, wants_base_url=True)
@comma_separated_list
def string_set(tokens, base_url): # -> tuple[Any, tuple[tuple[Literal['string'], Any] | tuple[Literal['attr()'], tuple[Any, Any | str, Any | str]] | tuple[LiteralString, tuple[Any, ...]] | tuple[Literal['content()'], Literal['text']] | tuple[Literal['content()'], Literal['text', 'before', 'after', 'first-letter', 'marker']] | tuple[str, tuple[Any, str]] | tuple[Literal['url'], tuple[str, str]] | tuple[Literal['url'], tuple[str, Any | str]] | tuple[Literal['quote'], Literal['open-quote', 'close-quote', 'no-open-quote', 'no-close-quote']] | tuple[Literal['leader()'], tuple[str, Any | str | None]] | None, ...]] | tuple[Literal['none'], tuple[()]] | None:
    """Validation for ``string-set``."""
    ...

@property()
def transform(tokens): # -> tuple[()] | tuple[Any, ...] | None:
    """Validation for ``transform``."""
    ...

@property()
@single_token
def appearance(token): # -> Literal['none', 'auto'] | None:
    """``appearance`` property validation."""
    ...

