"""
This type stub file was generated by pyright.
"""

from typing import Optional
from cachelib.file import FileSystemCache
from flask import Flask
from ..base import ServerSideSession, ServerSideSessionInterface

class CacheLibSession(ServerSideSession):
    ...


class CacheLibSessionInterface(ServerSideSessionInterface):
    """Uses any :class:`cachelib` backend as a session storage.

    :param client: A :class:`cachelib` backend instance.
    :param key_prefix: A prefix that is added to storage keys.
    :param use_signer: Whether to sign the session id cookie or not.
    :param permanent: Whether to use permanent session or not.
    :param sid_length: The length of the generated session id in bytes.
    :param serialization_format: The serialization format to use for the session data.
    """
    session_class = CacheLibSession
    ttl = ...
    def __init__(self, app: Flask = ..., client: Optional[FileSystemCache] = ..., key_prefix: str = ..., use_signer: bool = ..., permanent: bool = ..., sid_length: int = ..., serialization_format: str = ...) -> None:
        ...
    


