"""
This type stub file was generated by pyright.
"""

"""Find anchors, links, bookmarks and inputs in documents."""
def rectangle_aabb(matrix, pos_x, pos_y, width, height): # -> tuple[Any, Any, Any, Any]:
    """Apply a transformation matrix to an axis-aligned rectangle.

    Return its axis-aligned bounding box as ``(x1, y1, x2, y2)``.

    """
    ...

def gather_anchors(box, anchors, links, bookmarks, forms, parent_matrix=..., parent_form=...):
    """Gather anchors and other data related to specific positions in PDF.

    Currently finds anchors, links, bookmarks and forms.

    """
    ...

def make_page_bookmark_tree(page, skipped_levels, last_by_depth, previous_level, page_number, matrix):
    """Make a tree of all bookmarks in a given page."""
    ...

