"""
This type stub file was generated by pyright.
"""

"""Specific handling for some HTML elements, especially replaced elements.

Replaced elements (eg. <img> elements) are rendered externally and behave as an
atomic opaque box in CSS. In general, they may or may not have intrinsic
dimensions. But the only replaced elements currently supported in WeasyPrint
are images with intrinsic dimensions.

"""
HTML5_UA_COUNTER_STYLE = ...
HTML5_UA = ...
HTML5_UA_FORM = ...
HTML5_PH = ...
HTML5_UA_STYLESHEET = ...
HTML5_UA_FORM_STYLESHEET = ...
HTML5_PH_STYLESHEET = ...
HTML_WHITESPACE = ...
HTML_SPACE_SEPARATED_TOKENS_RE = ...
def ascii_lower(string):
    r"""Transform (only) ASCII letters to lower case: A-Z is mapped to a-z.

    This is used for `ASCII case-insensitive
    <https://whatwg.org/C#ascii-case-insensitive>`_ matching.

    This is different from the :meth:`str.lower` method of Unicode strings
    which also affect non-ASCII characters,
    sometimes mapping them into the ASCII range:

    >>> keyword = 'Bac\N{KELVIN SIGN}ground'
    >>> assert keyword.lower() == 'background'
    >>> assert ascii_lower(keyword) != keyword.lower()
    >>> assert ascii_lower(keyword) == 'bac\N{KELVIN SIGN}ground'

    """
    ...

def element_has_link_type(element, link_type): # -> bool:
    """Return whether element has a ``rel`` attribute with given link type."""
    ...

HTML_HANDLERS = ...
def handle_element(element, box, get_image_from_uri, base_url): # -> list[Any]:
    """Handle HTML elements that need special care.

    :returns: a (possibly empty) list of boxes.
    """
    ...

def handler(tag): # -> Callable[..., Any]:
    """Return a decorator registering a function handling ``tag`` elements."""
    ...

def make_replaced_box(element, box, image): # -> BlockReplacedBox | InlineReplacedBox:
    """Wrap an image in a replaced box.

    That box is either block-level or inline-level, depending on what the
    element should be.

    """
    ...

@handler('img')
def handle_img(element, box, get_image_from_uri, base_url): # -> list[BlockReplacedBox | InlineReplacedBox] | list[Any]:
    """Handle ``<img>`` elements.

    Return either an image or the alt-text.

    See: https://www.w3.org/TR/html5/embedded-content-1.html#the-img-element

    """
    ...

@handler('embed')
def handle_embed(element, box, get_image_from_uri, base_url): # -> list[BlockReplacedBox | InlineReplacedBox] | list[Any]:
    """Handle ``<embed>`` elements, return either an image or nothing.

    See: https://www.w3.org/TR/html5/embedded-content-0.html#the-embed-element

    """
    ...

@handler('object')
def handle_object(element, box, get_image_from_uri, base_url): # -> list[BlockReplacedBox | InlineReplacedBox] | list[Any]:
    """Handle ``<object>`` elements, return either an image or the fallback.

    See: https://www.w3.org/TR/html5/embedded-content-0.html#the-object-element

    """
    ...

@handler('colgroup')
def handle_colgroup(element, box, _get_image_from_uri, _base_url): # -> list[TableColumnGroupBox | Any]:
    """Handle the ``span`` attribute."""
    ...

@handler('col')
def handle_col(element, box, _get_image_from_uri, _base_url): # -> list[TableColumnBox] | list[Any | TableColumnBox]:
    """Handle the ``span`` attribute."""
    ...

@handler('{http://www.w3.org/2000/svg}svg')
def handle_svg(element, box, get_image_from_uri, base_url): # -> list[BlockReplacedBox | InlineReplacedBox] | list[Any]:
    """Handle ``<svg>`` elements.

    Return either an image or the fallback content.

    """
    ...

def get_html_metadata(html): # -> dict[str, Any]:
    """Get metadata dictionary out of HTML object.

    Relevant specs:

    https://www.whatwg.org/html#the-title-element
    https://www.whatwg.org/html#standard-metadata-names
    https://wiki.whatwg.org/wiki/MetaExtensions
    https://microformats.org/wiki/existing-rel-values#HTML5_link_type_extensions

    """
    ...

def strip_whitespace(string):
    """Use the HTML definition of "space character",
    not all Unicode Whitespace.

    https://www.whatwg.org/html#strip-leading-and-trailing-whitespace
    https://www.whatwg.org/html#space-character

    """
    ...

W3C_DATE_RE = ...
def parse_w3c_date(meta_name, string): # -> None:
    """Parse datetimes as defined by the W3C.

    See https://www.w3.org/TR/NOTE-datetime

    """
    ...

