"""
This type stub file was generated by pyright.
"""

import pydyf

"""Fetch and decode images in various formats."""
class ImageLoadingError(ValueError):
    """An error occured when loading an image.

    The image data is probably corrupted or in an invalid format.

    """
    @classmethod
    def from_exception(cls, exception): # -> Self:
        ...
    


class RasterImage:
    def __init__(self, pillow_image, image_id, image_data, filename=..., cache=..., orientation=..., options=...) -> None:
        ...
    
    def get_intrinsic_size(self, resolution, font_size): # -> tuple[Any, Any, float | Any]:
        ...
    
    def draw(self, stream, concrete_width, concrete_height, image_rendering): # -> None:
        ...
    
    def cache_image_data(self, data, filename=..., slot=...): # -> LazyLocalImage | LazyImage:
        ...
    
    def get_x_object(self, interpolate, dpi_ratio): # -> Stream:
        ...
    


class LazyImage(pydyf.Object):
    def __init__(self, cache, key, data) -> None:
        ...
    
    @property
    def data(self):
        ...
    


class LazyLocalImage(pydyf.Object):
    def __init__(self, filename) -> None:
        ...
    
    @property
    def data(self): # -> bytes:
        ...
    


class SVGImage:
    def __init__(self, tree, base_url, url_fetcher, context) -> None:
        ...
    
    def get_intrinsic_size(self, image_resolution, font_size): # -> tuple[float | Any | Literal[0] | None, float | Any | Literal[0] | None, float | Any | Literal[1] | None]:
        ...
    
    def draw(self, stream, concrete_width, concrete_height, image_rendering): # -> None:
        ...
    


def get_image_from_uri(cache, url_fetcher, options, url, forced_mime_type=..., context=..., orientation=...):
    """Get an Image instance from an image URI."""
    ...

def rotate_pillow_image(pillow_image, orientation): # -> Image:
    """Return a copy of a Pillow image with modified orientation.

    If orientation is not changed, return the same image.

    """
    ...

def process_color_stops(vector_length, positions): # -> list[Any | str]:
    """Give color stops positions on the gradient vector.

    ``vector_length`` is the distance between the starting point and ending
    point of the vector gradient.

    ``positions`` is a list of ``None``, or ``Dimension`` in px or %. 0 is the
    starting point, 1 the ending point.

    See https://drafts.csswg.org/css-images-3/#color-stop-syntax.

    Return processed color stops, as a list of floats in px.

    """
    ...

def normalize_stop_positions(positions): # -> tuple[Any, Any, list[int] | list[Any]]:
    """Normalize stop positions between 0 and 1.

    Return ``(first, last, positions)``.

    first: original position of the first position.
    last: original position of the last position.
    positions: list of positions between 0 and 1.

    """
    ...

def gradient_average_color(colors, positions): # -> Color | Literal['currentcolor'] | None:
    """
    https://drafts.csswg.org/css-images-3/#gradient-average-color
    """
    ...

class Gradient:
    def __init__(self, color_stops, repeating) -> None:
        ...
    
    def get_intrinsic_size(self, image_resolution, font_size): # -> tuple[None, None, None]:
        ...
    
    def draw(self, stream, concrete_width, concrete_height, _image_rendering): # -> None:
        ...
    
    def layout(self, width, height):
        """Get layout information about the gradient.

        width, height: Gradient box. Top-left is at coordinates (0, 0).

        Returns (scale_y, type_, points, positions, colors).

        scale_y: vertical scale of the gradient. float, used for ellipses
                 radial gradients. 1 otherwise.
        type_: gradient type.
        points: coordinates of useful points, depending on type_:
            'solid': None.
            'linear': (x0, y0, x1, y1)
                      coordinates of the starting and ending points.
            'radial': (cx0, cy0, radius0, cx1, cy1, radius1)
                      coordinates of the starting end ending circles
        positions: positions of the color stops. list of floats in between 0
                   and 1 (0 at the starting point, 1 at the ending point).
        colors: list of (r, g, b, a).

        """
        ...
    


class LinearGradient(Gradient):
    def __init__(self, color_stops, direction, repeating) -> None:
        ...
    
    def layout(self, width, height): # -> tuple[Literal[1], Literal['solid'], None, list[Any], list[Any]] | tuple[Literal[1], Literal['solid'], None, list[Any], list[Color | str | None]] | tuple[Literal[1], Literal['linear'], tuple[Any, Any, Any, Any], list[int] | list[Any], list[Any]]:
        ...
    


class RadialGradient(Gradient):
    def __init__(self, color_stops, shape, size, center, repeating) -> None:
        ...
    
    def layout(self, width, height): # -> tuple[Literal[1], Literal['solid'], None, list[Any], list[Any]] | tuple[Literal[1], Literal['solid'], None, list[Any], list[Color | str | None]] | tuple[float | Any, Literal['radial'], tuple[*tuple[Any, ...], Any] | Any | tuple[Any | Literal[0], ...] | tuple[Any | Literal['auto'], Any, Any | str, Any | Literal['auto'], Any, Any | str], list[Any] | Any | tuple[Any, *tuple[Any, ...]] | list[int], Any | list[Any]]:
        ...
    


