"""
This type stub file was generated by pyright.
"""

import contextlib
import logging

"""Logging setup.

The rest of the code gets the logger through this module rather than
``logging.getLogger`` to make sure that it is configured.

Logging levels are used for specific purposes:

- errors are used in ``LOGGER`` for unreachable or unusable external resources,
  including unreachable stylesheets, unreachables images and unreadable images;
- warnings are used in ``LOGGER`` for unknown or bad HTML/CSS syntaxes,
  unreachable local fonts and various non-fatal problems;
- infos are used in ``PROCESS_LOGGER`` to advertise rendering steps.

"""
LOGGER = ...
if not LOGGER.handlers:
    ...
PROGRESS_LOGGER = ...
class CallbackHandler(logging.Handler):
    """A logging handler that calls a function for every message."""
    def __init__(self, callback) -> None:
        ...
    


@contextlib.contextmanager
def capture_logs(logger=..., level=...): # -> Generator[list[Any], Any, None]:
    """Return a context manager that captures all logged messages."""
    ...

