"""
This type stub file was generated by pyright.
"""

"""Transformation matrix."""
class Matrix(list):
    def __init__(self, a=..., b=..., c=..., d=..., e=..., f=..., matrix=...) -> None:
        ...
    
    def __matmul__(self, other): # -> Matrix:
        ...
    
    @property
    def invert(self): # -> Matrix:
        ...
    
    @property
    def determinant(self):
        ...
    
    def transform_point(self, x, y):
        ...
    
    @property
    def values(self): # -> tuple[Any, Any, Any, Any, Any, Any]:
        ...
    


