"""
This type stub file was generated by pyright.
"""

"""Stacking contexts management."""
class StackingContext:
    """Stacking contexts define the paint order of all pieces of a document.

    https://www.w3.org/TR/CSS21/visuren.html#x43
    https://www.w3.org/TR/CSS21/zindex.html

    """
    def __init__(self, box, child_contexts, blocks, floats, blocks_and_cells, page) -> None:
        ...
    
    @classmethod
    def from_page(cls, page): # -> Self:
        ...
    
    @classmethod
    def from_box(cls, box, page, child_contexts=...): # -> Self:
        ...
    


