"""
This type stub file was generated by pyright.
"""

"""Convert specified property values into computed values."""
FONT_SIZE_KEYWORDS = ...
BORDER_WIDTH_KEYWORDS = ...
FONT_WEIGHT_RELATIVE = ...
PAGE_SIZES = ...
INITIAL_PAGE_SIZE = ...
COMPUTER_FUNCTIONS = ...
def register_computer(name): # -> Callable[..., Any]:
    """Decorator registering a property ``name`` for a function."""
    ...

def compute_attr(style, values):
    ...

@register_computer('background-image')
def background_image(style, name, values):
    """Compute lenghts in gradient background-image."""
    ...

@register_computer('background-position')
@register_computer('object-position')
def compute_position(style, name, values): # -> tuple[tuple[Any, Dimension | Any | Literal['auto', 'content', 'from-font', 0], Any, Dimension | Any | Literal['auto', 'content', 'from-font', 0]], ...]:
    """Compute lengths in background-position."""
    ...

@register_computer('transform-origin')
def length_or_percentage_tuple(style, name, values): # -> tuple[Dimension | Any | str | int, ...]:
    """Compute the lists of lengths that can be percentages."""
    ...

@register_computer('border-spacing')
@register_computer('size')
@register_computer('clip')
def length_tuple(style, name, values): # -> tuple[Dimension | Any | str | int, ...]:
    """Compute the properties with a list of lengths."""
    ...

@register_computer('break-after')
@register_computer('break-before')
def break_before_after(style, name, value): # -> Literal['page']:
    """Compute the ``break-before`` and ``break-after`` properties."""
    ...

@register_computer('top')
@register_computer('right')
@register_computer('left')
@register_computer('bottom')
@register_computer('margin-top')
@register_computer('margin-right')
@register_computer('margin-bottom')
@register_computer('margin-left')
@register_computer('height')
@register_computer('width')
@register_computer('min-width')
@register_computer('min-height')
@register_computer('max-width')
@register_computer('max-height')
@register_computer('padding-top')
@register_computer('padding-right')
@register_computer('padding-bottom')
@register_computer('padding-left')
@register_computer('text-indent')
@register_computer('hyphenate-limit-zone')
@register_computer('flex-basis')
@register_computer('text-underline-offset')
@register_computer('text-decoration-thickness')
def length(style, name, value, font_size=..., pixels_only=...): # -> Dimension | Literal['auto', 'content', 'from-font', 0]:
    """Compute a length ``value``."""
    ...

@register_computer('bleed-left')
@register_computer('bleed-right')
@register_computer('bleed-top')
@register_computer('bleed-bottom')
def bleed(style, name, value): # -> Dimension | Literal['auto', 'content', 'from-font', 0]:
    ...

@register_computer('letter-spacing')
def pixel_length(style, name, value): # -> Dimension | Literal['normal', 'auto', 'content', 'from-font', 0]:
    ...

@register_computer('background-size')
def background_size(style, name, values): # -> tuple[tuple[Dimension | Any | str | int, ...] | str, ...]:
    """Compute the ``background-size`` properties."""
    ...

@register_computer('image-orientation')
def image_orientation(style, name, values): # -> tuple[Any, Any] | Literal['none', 'from-image']:
    """Compute the ``image-orientation`` properties."""
    ...

@register_computer('border-top-width')
@register_computer('border-right-width')
@register_computer('border-left-width')
@register_computer('border-bottom-width')
@register_computer('column-rule-width')
@register_computer('outline-width')
def border_width(style, name, value): # -> int | Dimension | Literal['auto', 'content', 'from-font']:
    """Compute the ``border-*-width`` properties."""
    ...

@register_computer('border-image-slice')
@register_computer('mask-border-slice')
def border_image_slice(style, name, values): # -> tuple[*tuple[Any, ...], Literal['fill'] | None]:
    """Compute the ``border-image-slice`` property."""
    ...

@register_computer('border-image-width')
@register_computer('mask-border-width')
def border_image_width(style, name, values): # -> tuple[Any, ...]:
    """Compute the ``border-image-width`` property."""
    ...

@register_computer('border-image-outset')
@register_computer('mask-border-outset')
def border_image_outset(style, name, values): # -> tuple[int | float | Dimension | Any | str, ...]:
    """Compute the ``border-image-outset`` property."""
    ...

@register_computer('border-image-repeat')
@register_computer('mask-border-repeat')
def border_image_repeat(style, name, values):
    """Compute the ``border-image-repeat`` property."""
    ...

@register_computer('column-width')
@register_computer('outline-offset')
def length_pixels_only(style, name, value): # -> Dimension | Literal['auto', 'content', 'from-font', 0]:
    """Compute a pixel length property."""
    ...

@register_computer('border-top-left-radius')
@register_computer('border-top-right-radius')
@register_computer('border-bottom-left-radius')
@register_computer('border-bottom-right-radius')
def border_radius(style, name, values): # -> tuple[Dimension | Any | str | int, ...]:
    """Compute the ``border-*-radius`` properties."""
    ...

@register_computer('column-gap')
@register_computer('row-gap')
def gap(style, name, value): # -> Dimension | Literal['normal', 'auto', 'content', 'from-font', 0]:
    """Compute the ``*-gap`` properties."""
    ...

@register_computer('bookmark-label')
def bookmark_label(style, name, values): # -> tuple[Any, ...]:
    """Compute the ``bookmark-label`` property."""
    ...

@register_computer('string-set')
def string_set(style, name, values): # -> tuple[tuple[Any, tuple[Any, ...]], ...]:
    """Compute the ``string-set`` property."""
    ...

@register_computer('content')
def content(style, name, values): # -> tuple[Any, ...] | Literal['inhibit', 'contents']:
    """Compute the ``content`` property."""
    ...

@register_computer('display')
def display(style, name, value): # -> tuple[Literal['block'], Literal['table']] | tuple[Literal['block'], Literal['flow']] | tuple[Literal['block'], Literal['flow'], Literal['list-item']]:
    """Compute the ``display`` property."""
    ...

@register_computer('float')
def compute_float(style, name, value): # -> Literal['none']:
    """Compute the ``float`` property."""
    ...

@register_computer('font-size')
def font_size(style, name, value): # -> Dimension | Literal['auto', 'content', 'from-font', 0]:
    """Compute the ``font-size`` property."""
    ...

@register_computer('font-weight')
def font_weight(style, name, value): # -> int:
    """Compute the ``font-weight`` property."""
    ...

@register_computer('grid-template-columns')
@register_computer('grid-template-rows')
def grid_template(style, name, values): # -> tuple[Any, ...] | Literal['none']:
    """Compute the ``grid-template-*`` properties."""
    ...

@register_computer('grid-auto-columns')
@register_computer('grid-auto-rows')
def grid_auto(style, name, values): # -> tuple[Any, ...]:
    """Compute the ``grid-auto-*`` properties."""
    ...

@register_computer('line-height')
def line_height(style, name, value): # -> tuple[Literal['NUMBER'], Any] | tuple[Literal['PIXELS'], Any | Dimension | Literal['auto', 'content', 'from-font', 0]] | Literal['normal']:
    """Compute the ``line-height`` property."""
    ...

@register_computer('anchor')
def anchor(style, name, values): # -> None:
    """Compute the ``anchor`` property."""
    ...

@register_computer('link')
def link(style, name, values): # -> tuple[Literal['url'], tuple[str, str]] | tuple[Literal['url'], tuple[str, Any | str]] | None:
    """Compute the ``link`` property."""
    ...

@register_computer('lang')
def lang(style, name, values): # -> None:
    """Compute the ``lang`` property."""
    ...

@register_computer('tab-size')
def tab_size(style, name, value): # -> int | Dimension | Literal['auto', 'content', 'from-font']:
    """Compute the ``tab-size`` property."""
    ...

@register_computer('transform')
def transform(style, name, value): # -> tuple[Any, ...]:
    """Compute the ``transform`` property."""
    ...

@register_computer('vertical-align')
def vertical_align(style, name, value): # -> Dimension | Literal['baseline', 'middle', 'text-top', 'text-bottom', 'top', 'bottom', 'auto', 'content', 'from-font', 0]:
    """Compute the ``vertical-align`` property."""
    ...

@register_computer('word-spacing')
def word_spacing(style, name, value): # -> Dimension | Literal[0, 'auto', 'content', 'from-font']:
    """Compute the ``word-spacing`` property."""
    ...

def strut_layout(style, context=...): # -> tuple[Literal[0], Literal[0]] | tuple[Any, Any]:
    """Return a tuple of the used value of ``line-height`` and the baseline.

    The baseline is given from the top edge of line height.

    """
    ...

def character_ratio(style, character): # -> float:
    """Return the ratio of 1ex/font_size or 1ch/font_size."""
    ...

