"""
This type stub file was generated by pyright.
"""

"""Implement counter styles.

These are defined in CSS Counter Styles Level 3:
https://www.w3.org/TR/css-counter-styles-3/#counter-style-system

"""
def symbol(string_or_url): # -> Literal['']:
    """Create a string from a symbol."""
    ...

def parse_counter_style_name(tokens, counter_style): # -> None:
    ...

class CounterStyle(dict):
    """Counter styles dictionary.

    Keep a list of counter styles defined by ``@counter-style`` rules, indexed
    by their names.

    See https://www.w3.org/TR/css-counter-styles-3/.

    """
    def resolve_counter(self, counter_name, previous_types=...): # -> dict[str, Any] | None:
        ...
    
    def render_value(self, counter_value, counter_name=..., counter=..., previous_types=...):
        """Generate the counter representation.

        See https://www.w3.org/TR/css-counter-styles-3/#generate-a-counter

        """
        ...
    
    def render_marker(self, counter_name, counter_value): # -> Literal['']:
        """Generate the content of a ::marker pseudo-element."""
        ...
    
    def copy(self): # -> CounterStyle:
        ...
    


