"""
This type stub file was generated by pyright.
"""

"""Handle media queries.

https://www.w3.org/TR/mediaqueries-4/

"""
def evaluate_media_query(query_list, device_media_type): # -> bool:
    """Return the boolean evaluation of `query_list` for the given
    `device_media_type`.

    :attr query_list: a cssutilts.stlysheets.MediaList
    :attr device_media_type: a media type string (for now)

    """
    ...

def parse_media_query(tokens): # -> list[str] | list[Any] | None:
    ...

