"""
This type stub file was generated by pyright.
"""

"""Handle target-counter, target-counters and target-text.

The TargetCollector is a structure providing required targets' counter_values
and stuff needed to build pending targets later, when the layout of all
targeted anchors has been done.

"""
class TargetLookupItem:
    """Item controlling pending targets and page based target counters.

    Collected in the TargetCollector's ``target_lookup_items``.

    """
    def __init__(self, state=...) -> None:
        ...
    


class CounterLookupItem:
    """Item controlling page based counters.

    Collected in the TargetCollector's ``counter_lookup_items``.

    """
    def __init__(self, parse_again, missing_counters, missing_target_counters) -> None:
        ...
    


def anchor_name_from_token(anchor_token): # -> None:
    """Get anchor name from string or uri token."""
    ...

class TargetCollector:
    """Collector of HTML targets used by CSS content with ``target-*``."""
    def __init__(self) -> None:
        ...
    
    def collect_anchor(self, anchor_name): # -> None:
        """Create a TargetLookupItem for the given `anchor_name``."""
        ...
    
    def lookup_target(self, anchor_token, source_box, css_token, parse_again):
        """Get a TargetLookupItem corresponding to ``anchor_token``.

        If it is already filled by a previous anchor-element, the status is
        'up-to-date'. Otherwise, it is 'pending', we must parse the whole
        tree again.

        """
        ...
    
    def store_target(self, anchor_name, target_counter_values, target_box): # -> None:
        """Store a target called ``anchor_name``.

        If there is a pending TargetLookupItem, it is updated. Only previously
        collected anchors are stored.

        """
        ...
    
    def collect_missing_counters(self, parent_box, css_token, parse_again_function, missing_counters, missing_target_counters): # -> None:
        """Collect missing (probably page-based) counters during formatting.

        The ``missing_counters`` are re-used during pagination.

        The ``missing_link`` attribute added to the parent_box is required to
        connect the paginated boxes to their originating ``parent_box``.

        """
        ...
    
    def check_pending_targets(self): # -> None:
        """Check pending targets if needed."""
        ...
    
    def cache_target_page_counters(self, anchor_name, page_counter_values, page_maker_index, page_maker): # -> None:
        """Store target's current ``page_maker_index`` and page counter values.

        Eventually update associated targeting boxes.

        """
        ...
    


