
CREATE TABLE IF NOT EXISTS 92_indicatifs_tel (
    id INT PRIMARY KEY,
    pays VARCHAR(255) NOT NULL,
    indicatif VARCHAR(6) NOT NULL
);
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (1, 'France', '33');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (2, 'Afghanistan', '93');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (3, 'Afrique du sud', '27');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (4, 'Albanie', '355');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (5, 'Algérie', '213');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (6, 'Allemagne', '49');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (7, 'Andorre', '376');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (8, 'Angleterre', '44');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (9, 'Angola', '244');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (10, 'Anguilla', '1');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (11, 'Antigua et Barbuda', '1');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (12, 'Antilles néerlandaises', '599');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (13, 'Arabie saoudite', '966');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (14, 'Argentine', '54');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (15, 'Arménie', '374');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (16, 'Aruba', '297');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (17, 'Ascension', '247');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (18, 'Australie', '61');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (19, 'Autriche', '43');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (20, 'Azerbaïdjan', '994');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (21, 'Bahamas', '1');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (22, 'Bahreïn', '973');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (23, 'Bangladesh', '880');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (24, 'Barbade', '1');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (25, 'Belgique', '32');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (26, 'Bélize', '501');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (27, 'Bénin', '229');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (28, 'Bermudes', '1');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (29, 'Bhoutan', '975');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (30, 'Biélorussie', '375');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (31, 'Birmanie', '95');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (32, 'Bolivie', '591');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (33, 'Bosnie-Herzégovine', '387');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (34, 'Botswana', '267');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (35, 'Brésil', '55');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (36, 'Brunei', '673');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (37, 'Bulgarie', '359');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (38, 'Burkina Faso', '226');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (39, 'Burundi', '257');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (40, 'Cambodge', '855');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (41, 'Cameroun', '237');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (42, 'Canada', '1');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (43, 'Cap vert', '238');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (44, 'Centrafrique', '236');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (45, 'Chili', '56');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (46, 'Chine', '86');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (47, 'Chypre', '357');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (48, 'Colombie', '57');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (49, 'Comores', '269');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (50, 'Congo', '242');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (51, 'Corée du Nord', '850');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (52, 'Corée du sud', '82');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (53, 'Costa rica', '506');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (54, 'Côte d''Ivoire', '225');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (55, 'Croatie', '385');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (56, 'Cuba', '53');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (57, 'Curaçao', '599');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (58, 'Danemark', '45');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (59, 'Diego garcia', '246');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (60, 'Djibouti', '253');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (61, 'Dominique', '1');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (62, 'Écosse', '44');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (63, 'Egypte', '20');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (64, 'Émirats arabes unis', '971');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (65, 'Equateur', '593');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (66, 'Érythrée', '291');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (67, 'Espagne', '34');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (68, 'Estonie', '372');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (69, 'Etats-Unis', '1');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (70, 'Éthiopie', '251');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (71, 'Fidji', '679');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (72, 'Finlande', '358');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (73, 'Gabon', '241');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (74, 'Gambie', '220');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (75, 'Géorgie', '995');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (76, 'Ghana', '233');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (77, 'Gibraltar', '350');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (78, 'Grèce', '30');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (79, 'Grenade', '1');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (80, 'Groenland', '299');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (81, 'Guadeloupe', '590');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (82, 'Guam', '1');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (83, 'Guatemala', '502');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (84, 'Guinée', '224');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (85, 'Guinée équatoriale', '240');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (86, 'Guinée-Bissau', '245');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (87, 'Guyana', '592');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (88, 'Guyane', '594');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (89, 'Haïti', '509');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (90, 'Honduras', '504');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (91, 'Hong kong', '852');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (92, 'Hongrie', '36');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (93, 'Île Maurice', '230');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (94, 'Île Norfolk', '6723');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (95, 'Île Sainte Hélène', '290');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (96, 'Île Tristan da Cunha', '290');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (97, 'Îles Caïmans', '1');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (98, 'Iles cook', '682');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (99, 'Îles Féroé', '298');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (100, 'Îles Malouines', '500');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (101, 'Îles Mariannes du Nord', '1');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (102, 'Îles Marshall', '692');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (103, 'Îles Pitcairn', '64');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (104, 'Îles Turques et Caïques', '1');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (105, 'Îles Vierges britanniques', '1');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (106, 'Îles Vierges des États-Unis', '1');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (107, 'Inde', '91');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (108, 'Indonésie', '62');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (109, 'Irak', '964');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (110, 'Iran', '98');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (111, 'Irlande', '353');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (112, 'Irlande du Nord', '44');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (113, 'Islande', '354');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (114, 'Israël', '972');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (115, 'Italie', '39');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (116, 'Jamaïque', '1');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (117, 'Japon', '81');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (118, 'Jordanie', '962');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (119, 'Kazakhstan', '7');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (120, 'Kenya', '254');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (121, 'Kirghizistan', '996');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (122, 'Kiribati', '686');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (123, 'Kosovo', '383');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (124, 'Koweït', '965');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (125, 'Laos', '856');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (126, 'Lesotho', '266');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (127, 'Lettonie', '371');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (128, 'Liban', '961');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (129, 'Liberia', '231');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (130, 'Libye', '218');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (131, 'Liechtenstein', '423');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (132, 'Lituanie', '370');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (133, 'Luxembourg', '352');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (134, 'Macao', '853');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (135, 'Macédoine', '389');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (136, 'Madagascar', '261');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (137, 'Malaisie', '60');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (138, 'Malawi', '265');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (139, 'Maldives', '960');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (140, 'Mali', '223');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (141, 'Malte', '356');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (142, 'Maroc', '212');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (143, 'Martinique', '596');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (144, 'Mauritanie', '222');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (145, 'Mayotte', '262');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (146, 'Mexique', '52');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (147, 'Micronésie', '691');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (148, 'Moldavie', '373');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (149, 'Monaco', '377');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (150, 'Mongolie', '976');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (151, 'Monténégro', '382');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (152, 'Montserrat', '1');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (153, 'Mozambique', '258');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (154, 'Namibie', '264');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (155, 'Nauru', '674');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (156, 'Népal', '977');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (157, 'Nicaragua', '505');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (158, 'Niger', '227');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (159, 'Nigeria', '234');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (160, 'Niue', '683');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (161, 'Norvège', '47');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (162, 'Nouvelle Calédonie', '687');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (163, 'Nouvelle Zélande', '64');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (164, 'Oman', '968');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (165, 'Ouganda', '256');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (166, 'Ouzbékistan', '998');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (167, 'Pakistan', '92');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (168, 'Palaos', '680');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (169, 'Palestine', '970');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (170, 'Panama', '507');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (171, 'Papouasie Nouvelle Guinée', '675');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (172, 'Paraguay', '595');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (173, 'Pays Bas', '31');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (174, 'Pays de Galles', '44');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (175, 'Pérou', '51');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (176, 'Philippines', '63');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (177, 'Pologne', '48');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (178, 'Polynésie française', '689');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (179, 'Porto Rico', '1');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (180, 'Portugal', '351');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (181, 'Qatar', '974');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (182, 'République démocratique du congo', '243');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (183, 'République dominicaine', '1');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (184, 'République tchèque', '420');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (185, 'Réunion', '262');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (186, 'Roumanie', '40');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (187, 'Royaume Uni', '44');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (188, 'Russie', '7');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (189, 'Rwanda', '250');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (190, 'Saint Barthélemy', '590');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (191, 'Saint Christophe et Niévès', '1');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (192, 'Saint Marin', '378');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (193, 'Saint Martin (France)', '590');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (194, 'Saint Martin (Pays bas)', '1');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (195, 'Saint Pierre et Miquelon', '508');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (196, 'Saint Vincent et les Grenadines', '1');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (197, 'Sainte Lucie', '1');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (198, 'Salomon', '677');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (199, 'Salvador', '503');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (200, 'Samoa', '685');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (201, 'Samoa américaines', '1');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (202, 'Sao Tomé et Principe', '239');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (203, 'Sénégal', '221');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (204, 'Serbie', '381');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (205, 'Seychelles', '248');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (206, 'Sierra Leone', '232');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (207, 'Singapour', '65');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (208, 'Slovaquie', '421');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (209, 'Slovénie', '386');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (210, 'Somalie', '252');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (211, 'Soudan', '249');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (212, 'Soudan du Sud', '211');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (213, 'Sri Lanka', '94');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (214, 'Suède', '46');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (215, 'Suisse', '41');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (216, 'Suriname', '597');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (217, 'Swaziland', '268');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (218, 'Syrie', '963');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (219, 'Tadjikistan', '992');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (220, 'Taiwan', '886');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (221, 'Tanzanie', '255');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (222, 'Tchad', '235');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (223, 'Thailande', '66');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (224, 'Timor oriental', '670');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (225, 'Togo', '228');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (226, 'Tokelau', '690');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (227, 'Tonga', '676');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (228, 'Trinité et Tobago', '1');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (229, 'Tunisie', '216');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (230, 'Turkménistan', '993');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (231, 'Turquie', '90');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (232, 'Tuvalu', '688');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (233, 'Ukraine', '380');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (234, 'Uruguay', '598');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (235, 'Vanuatu', '678');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (236, 'Vatican', '379');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (237, 'Venezuela', '58');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (238, 'Viet Nam', '84');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (239, 'Wallis et Futuna', '681');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (240, 'Yémen', '967');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (241, 'Zambie', '260');
INSERT INTO 92_indicatifs_tel (id, pays, indicatif) VALUES (242, 'Zimbabwe', '263');
