"""
This type stub file was generated by pyright.
"""

"""Interface with external libraries managing fonts installed on the system."""
class FontConfiguration:
    """A Fontconfig font configuration.

    Keep a list of fonts, including fonts installed on the system, fonts
    installed for the current user, and fonts referenced by cascading
    stylesheets.

    When created, an instance of this class gathers available fonts. It can
    then be given to :class:`weasyprint.HTML` methods or to
    :class:`weasyprint.CSS` to find fonts in ``@font-face`` rules.

    """
    _folder = ...
    def __init__(self) -> None:
        """Create a Fontconfig font configuration.

        See Behdad's blog:
        https://mces.blogspot.fr/2015/05/how-to-use-custom-application-fonts.html

        """
        ...
    
    def add_font_face(self, rule_descriptors, url_fetcher):
        """Add a font face to the Fontconfig configuration."""
        ...
    
    def __del__(self): # -> None:
        """Clean a font configuration for a document."""
        ...
    


def font_features(font_kerning=..., font_variant_ligatures=..., font_variant_position=..., font_variant_caps=..., font_variant_numeric=..., font_variant_alternates=..., font_variant_east_asian=..., font_feature_settings=...): # -> dict[Any, Any]:
    """Get the font features from the different properties in style.

    See https://www.w3.org/TR/css-fonts-3/#feature-precedence

    """
    ...

def get_font_description(style):
    """Get font description string out of given style."""
    ...

def get_pango_font_hb_face(pango_font):
    """Get Harfbuzz face out of given Pango font."""
    ...

def get_hb_object_data(hb_object, ot_color=..., glyph=...): # -> bytes | str | list[Any] | None:
    """Get binary data out of given Harfbuzz font or face.

    If ``ot_color`` is 'svg', return the SVG color glyph reference. If it’s 'png',
    return the PNG color glyph reference. Otherwise, return the whole face blob.

    """
    ...

def get_pango_font_key(pango_font): # -> tuple[Any, Any, Any]:
    """Get key corresponding to given Pango font."""
    ...

