"""
This type stub file was generated by pyright.
"""

from typing import Optional
from mypy_boto3_dynamodb.service_resource import DynamoDBServiceResource
from flask import Flask
from ..base import ServerSideSession, ServerSideSessionInterface

class DynamoDBSession(ServerSideSession):
    ...


class DynamoDBSessionInterface(ServerSideSessionInterface):
    """A Session interface that uses dynamodb as backend. (`boto3` required)

    :param client: A ``DynamoDBServiceResource`` instance.
    :param key_prefix: A prefix that is added to all DynamoDB store keys.
    :param use_signer: Whether to sign the session id cookie or not.
    :param permanent: Whether to use permanent session or not.
    :param sid_length: The length of the generated session id in bytes.
    :param table_name: DynamoDB table name to store the session.

    .. versionadded:: 0.6
        The `sid_length` parameter was added.

    .. versionadded:: 0.2
        The `use_signer` parameter was added.
    """
    session_class = DynamoDBSession
    def __init__(self, app: Flask, client: Optional[DynamoDBServiceResource] = ..., key_prefix: str = ..., use_signer: bool = ..., permanent: bool = ..., sid_length: int = ..., serialization_format: str = ..., table_name: str = ...) -> None:
        ...
    


