"""
This type stub file was generated by pyright.
"""

import operator
from math import floor
from xml.etree import ElementTree
from ..formatting_structure import boxes
from ..images import SVGImage
from ..layout import replaced
from ..layout.background import BackgroundLayer
from ..matrix import Matrix
from ..stacking import StackingContext
from .border import draw_border, draw_line, draw_outline, rounded_box, set_mask_border
from .color import styled_color
from .text import draw_text

"""Take an "after layout" box tree and draw it onto a pydyf stream."""
def draw_page(page, stream): # -> None:
    """Draw the given PageBox."""
    ...

def draw_stacking_context(stream, stacking_context): # -> None:
    """Draw a ``stacking_context`` on ``stream``."""
    ...

def draw_background(stream, bg, clip_box=..., bleed=..., marks=...): # -> None:
    """Draw the background color and image to a ``pdf.stream.Stream``.

    If ``clip_box`` is set to ``False``, the background is not clipped to the
    border box of the background, but only to the painting area.

    """
    ...

def draw_background_image(stream, layer, image_rendering): # -> None:
    ...

def draw_table(stream, table): # -> None:
    ...

def draw_collapsed_borders(stream, table): # -> None:
    """Draw borders of table cells when they collapse."""
    ...

def draw_replacedbox(stream, box): # -> None:
    """Draw the given :class:`boxes.ReplacedBox` to a ``pdf.stream.Stream``."""
    ...

def draw_inline_level(stream, page, box, offset_x=..., text_overflow=..., block_ellipsis=...): # -> None:
    ...

def draw_block_level(page, stream, blocks_and_cells): # -> None:
    ...

