"""
This type stub file was generated by pyright.
"""

"""Draw borders."""
SIDES = ...
def set_mask_border(stream, box): # -> None:
    """Set ``box`` mask border as alpha state on ``stream``."""
    ...

def draw_column_rules(stream, box): # -> None:
    """Draw the column rules to a ``pdf.stream.Stream``."""
    ...

def draw_border(stream, box): # -> None:
    """Draw the box borders and column rules to a ``pdf.stream.Stream``."""
    ...

def draw_border_image(box, stream, image, border_slice, border_repeat, border_outset, border_width): # -> None:
    """Draw ``image`` as a border image for ``box`` on ``stream`` as specified."""
    ...

def clip_border_segment(stream, style, width, side, border_box, border_widths=..., radii=...):
    """Clip one segment of box border.

    The strategy is to remove the zones not needed because of the style or the
    side before painting.

    """
    ...

def draw_rounded_border(stream, box, style, color): # -> None:
    ...

def draw_rect_border(stream, box, widths, style, color): # -> None:
    ...

def draw_line(stream, x1, y1, x2, y2, thickness, style, color, offset=...): # -> None:
    ...

def draw_outline(stream, box): # -> None:
    ...

def rounded_box(stream, radii): # -> None:
    """Draw the path of the border radius box.

    ``widths`` is a tuple of the inner widths (top, right, bottom, left) from
    the border box. Radii are adjusted from these values. Default is (0, 0, 0,
    0).

    """
    ...

