"""
This type stub file was generated by pyright.
"""

"""Draw colors."""
def get_color(style, key):
    """Return color, taking care of possible currentColor value."""
    ...

def darken(color): # -> Color | Literal['currentcolor'] | None:
    """Return a darker color."""
    ...

def lighten(color): # -> Color | Literal['currentcolor'] | None:
    """Return a lighter color."""
    ...

def styled_color(style, color, side): # -> Color | tuple[Color | Literal['currentcolor'] | None, Color | Literal['currentcolor'] | None] | Literal['currentcolor'] | None:
    """Return inset, outset, ridge and groove border colors."""
    ...

