"""
This type stub file was generated by pyright.
"""

"""Draw text."""
def draw_text(stream, textbox, offset_x, text_overflow, block_ellipsis): # -> None:
    """Draw a textbox to a pydyf stream."""
    ...

def draw_emojis(stream, font_size, x, y, emojis): # -> None:
    """Draw list of emojis."""
    ...

def draw_first_line(stream, textbox, text_overflow, block_ellipsis, matrix):
    """Draw the given ``textbox`` line to the document ``stream``."""
    ...

def draw_text_decoration(stream, textbox, offset_x, offset_y, thickness, color): # -> None:
    """Draw text-decoration of ``textbox`` to a ``pdf.stream.Stream``."""
    ...

