"""
This type stub file was generated by pyright.
"""

import pydyf
from importlib.resources import files
from tinycss2.color4 import D50, D65
from .. import Attachment, VERSION
from ..html import W3C_DATE_RE
from ..logger import LOGGER, PROGRESS_LOGGER
from ..matrix import Matrix
from . import debug, pdfa, pdfua
from .fonts import build_fonts_dictionary
from .stream import Stream
from .tags import add_tags
from .anchors import add_annotations, add_forms, add_links, add_outlines, resolve_links, write_pdf_attachment

"""PDF generation management."""
VARIANTS = ...
def generate_pdf(document, target, zoom, **options):
    ...

