"""
This type stub file was generated by pyright.
"""

"""Insert anchors, links, bookmarks and inputs in PDFs."""
def add_links(links_and_anchors, matrix, pdf, page, names, tags): # -> None:
    """Include hyperlinks in given PDF page."""
    ...

def add_outlines(pdf, bookmarks, parent=...): # -> tuple[list[Any], int]:
    """Include bookmark outlines in PDF."""
    ...

def add_forms(forms, matrix, pdf, page, resources, stream, font_map):
    """Include form inputs in PDF."""
    ...

def add_annotations(links, matrix, document, pdf, page, annot_files, compress): # -> None:
    """Include annotations in PDF."""
    ...

def write_pdf_attachment(pdf, attachment, compress): # -> Dictionary | None:
    """Write an attachment to the PDF stream."""
    ...

def resolve_links(pages): # -> Generator[tuple[list[Any], Any], Any, None]:
    """Resolve internal hyperlinks.

    Links to a missing anchor are removed with a warning.

    If multiple anchors have the same name, the first one is used.

    :returns:
        A generator yielding lists (one per page) like :attr:`Page.links`,
        except that ``target`` for internal hyperlinks is
        ``(page_number, x, y)`` instead of an anchor name.
        The page number is a 0-based index into the :attr:`pages` list,
        and ``x, y`` are in CSS pixels from the top-left of the page.

    """
    ...

