"""
This type stub file was generated by pyright.
"""

"""PDF generation with debug information."""
def debug(pdf, metadata, document, page_streams, attachments, compress): # -> None:
    """Set debug PDF metadata."""
    ...

VARIANTS = ...
