"""
This type stub file was generated by pyright.
"""

"""Fonts integration in PDF."""
class Font:
    def __init__(self, pango_font, description, font_size) -> None:
        ...
    
    def clean(self, cmap, hinting):
        """Remove useless data from font."""
        ...
    
    @property
    def type(self): # -> Literal['otf', 'ttf']:
        ...
    
    def subset(self, cmap, hinting): # -> None:
        """Remove unused glyphs and tables from font."""
        ...
    


def build_fonts_dictionary(pdf, fonts, compress, subset, options): # -> Dictionary:
    """Build PDF dictionary for fonts."""
    ...

