"""
This type stub file was generated by pyright.
"""

"""PDF metadata stream generation."""
NS = ...
def add_metadata(pdf, metadata, variant, version, conformance, compress): # -> None:
    """Add PDF stream of metadata.

    Described in ISO-32000-1:2008, 14.3.2.

    """
    ...

def generate_rdf_metadata(metadata, variant, version, conformance): # -> Any:
    """Generate RDF metadata as a bytestring.

    Might be replaced by DocumentMetadata.rdf_metadata_generator().

    """
    ...

