"""
This type stub file was generated by pyright.
"""

"""PDF/A generation."""
def pdfa(pdf, metadata, document, page_streams, attachments, compress, version, variant): # -> None:
    """Set metadata for PDF/A documents."""
    ...

VARIANTS = ...
