"""
This type stub file was generated by pyright.
"""

"""PDF/UA generation."""
def pdfua(pdf, metadata, document, page_streams, attachments, compress, version): # -> None:
    """Set metadata for PDF/UA documents."""
    ...

VARIANTS = ...
