"""
This type stub file was generated by pyright.
"""

import pydyf
from contextlib import contextmanager

"""PDF stream."""
class Stream(pydyf.Stream):
    """PDF stream object with extra features."""
    def __init__(self, fonts, page_rectangle, resources, images, tags, *args, **kwargs) -> None:
        ...
    
    def clone(self, **kwargs): # -> Stream:
        ...
    
    @property
    def ctm(self): # -> Matrix:
        ...
    
    def push_state(self): # -> None:
        ...
    
    def pop_state(self): # -> None:
        ...
    
    def transform(self, a=..., b=..., c=..., d=..., e=..., f=...): # -> None:
        ...
    
    def begin_text(self): # -> None:
        ...
    
    def end_text(self): # -> None:
        ...
    
    def set_color(self, color, stroke=...): # -> None:
        ...
    
    def set_font_size(self, font, size): # -> None:
        ...
    
    def set_state(self, state): # -> None:
        ...
    
    def set_alpha(self, alpha, stroke=..., fill=...): # -> None:
        ...
    
    def set_alpha_state(self, x, y, width, height, mode=...): # -> Stream:
        ...
    
    def set_blend_mode(self, mode): # -> None:
        ...
    
    def add_font(self, pango_font): # -> tuple[Any, Any]:
        ...
    
    def add_group(self, x, y, width, height): # -> Stream:
        ...
    
    def add_image(self, image, interpolate, ratio): # -> str:
        ...
    
    def add_pattern(self, x, y, width, height, repeat_width, repeat_height, matrix): # -> Stream:
        ...
    
    def add_shading(self, shading_type, color_space, domain, coords, extend, function): # -> Dictionary:
        ...
    
    @contextmanager
    def stacked(self): # -> Generator[None, Any, None]:
        """Save and restore stream context when used with the ``with`` keyword."""
        ...
    
    @contextmanager
    def marked(self, box, tag): # -> Generator[None, Any, None]:
        ...
    
    @contextmanager
    def artifact(self): # -> Generator[None, Any, None]:
        ...
    
    @staticmethod
    def create_interpolation_function(domain, c0, c1, n): # -> Dictionary:
        ...
    
    @staticmethod
    def create_stitching_function(domain, encode, bounds, sub_functions): # -> Dictionary:
        ...
    


