"""
This type stub file was generated by pyright.
"""

from .min_max import handle_min_max_width

"""Absolutely positioned boxes management."""
class AbsolutePlaceholder:
    """Left where an absolutely-positioned box was taken out of the flow."""
    def __init__(self, box) -> None:
        ...
    
    def set_laid_out_box(self, new_box): # -> None:
        ...
    
    def translate(self, dx=..., dy=..., ignore_floats=...): # -> None:
        ...
    
    def copy(self): # -> AbsolutePlaceholder:
        ...
    
    def __getattr__(self, name): # -> Any:
        ...
    
    def __setattr__(self, name, value): # -> None:
        ...
    
    def __repr__(self): # -> Any:
        ...
    


@handle_min_max_width
def absolute_width(box, context, cb_x, cb_y, cb_width, cb_height): # -> tuple[Any | bool, Any | Literal[0]]:
    ...

def absolute_height(box, context, cb_x, cb_y, cb_width, cb_height): # -> tuple[bool, Any | Literal[0]]:
    ...

def absolute_block(context, box, containing_block, fixed_boxes, bottom_space, skip_stack, cb_x, cb_y, cb_width, cb_height): # -> tuple[Any, Any]:
    ...

def absolute_layout(context, placeholder, containing_block, fixed_boxes, bottom_space, skip_stack): # -> None:
    """Set the width of absolute positioned ``box``."""
    ...

def absolute_box_layout(context, box, containing_block, fixed_boxes, bottom_space, skip_stack): # -> tuple[Any, Any | None]:
    ...

def absolute_replaced(context, box, cb_x, cb_y, cb_width, cb_height):
    ...

