"""
This type stub file was generated by pyright.
"""

"""Manage background position and size."""
Background = ...
BackgroundLayer = ...
def box_rectangle(box, which_rectangle): # -> tuple[Any, Any, Any, Any]:
    ...

def layout_box_backgrounds(page, box, get_image_from_uri, layout_children=..., style=...): # -> None:
    """Fetch and position background images."""
    ...

def layout_background_layer(box, page, resolution, image, size, clip, repeat, origin, position, attachment):
    ...

def layout_backgrounds(page, get_image_from_uri): # -> None:
    """Layout backgrounds on the page box and on its children.

    This function takes care of the canvas background, taken from the root
    elememt or a <body> child of the root element.

    See https://www.w3.org/TR/CSS21/colors.html#background

    """
    ...

