"""
This type stub file was generated by pyright.
"""

from .min_max import handle_min_max_width

"""Page breaking and layout for block-level and block-container boxes."""
def block_level_layout(context, box, bottom_space, skip_stack, containing_block, page_is_empty=..., absolute_boxes=..., fixed_boxes=..., adjoining_margins=..., discard=..., max_lines=...): # -> tuple[*tuple[Any, ...], None] | tuple[*tuple[Any | BlockReplacedBox | dict[str, Any] | list[Any] | Literal[False] | None, ...], None]:
    """Lay out the block-level ``box``."""
    ...

def block_level_layout_switch(context, box, bottom_space, skip_stack, containing_block, page_is_empty, absolute_boxes, fixed_boxes, adjoining_margins, discard, max_lines): # -> tuple[*tuple[Any, ...], None] | tuple[*tuple[Any | BlockReplacedBox | dict[str, Any] | list[Any] | Literal[False] | None, ...], None]:
    """Call the layout function corresponding to the ``box`` type."""
    ...

def block_box_layout(context, box, bottom_space, skip_stack, containing_block, page_is_empty, absolute_boxes, fixed_boxes, adjoining_margins, discard, max_lines): # -> tuple[*tuple[Any, ...], None]:
    """Lay out the block ``box``."""
    ...

@handle_min_max_width
def block_level_width(box, containing_block): # -> None:
    """Set the ``box`` width."""
    ...

def relative_positioning(box, containing_block): # -> None:
    """Translate the ``box`` if it is relatively positioned."""
    ...

def block_container_layout(context, box, bottom_space, skip_stack, page_is_empty, absolute_boxes, fixed_boxes, adjoining_margins, discard, max_lines):
    """Set the ``box`` height."""
    ...

def collapse_margin(adjoining_margins): # -> int:
    """Get the amount of collapsed margin for a list of adjoining margins."""
    ...

def block_level_page_break(sibling_before, sibling_after): # -> Literal['auto', 'left', 'right', 'recto', 'verso']:
    """Get the correct page break value between siblings.

    Return the value of ``page-break-before`` or ``page-break-after`` that
    "wins" for boxes that meet at the margin between two sibling boxes.

    For boxes before the margin, the 'page-break-after' value is considered;
    for boxes after the margin the 'page-break-before' value is considered.

    * 'avoid' takes priority over 'auto'
    * 'page' takes priority over 'avoid' or 'auto'
    * 'left' or 'right' take priority over 'always', 'avoid' or 'auto'
    * Among 'left' and 'right', later values in the tree take priority.

    See https://drafts.csswg.org/css-page-3/#allowed-pg-brk

    """
    ...

def block_level_page_name(sibling_before, sibling_after): # -> None:
    """Return the next page name when siblings don't have the same names."""
    ...

def find_earlier_page_break(context, children, absolute_boxes, fixed_boxes): # -> tuple[Any, dict[int, Any]] | tuple[Any | list[Any], dict[Any, None] | dict[Any, Any]] | None:
    """Find the last possible page break in ``children``.

    Because of a `page-break-before: avoid` or a `page-break-after: avoid` we
    need to find an earlier page break opportunity inside `children`.

    Absolute or fixed placeholders removed from children should also be
    removed from `absolute_boxes` or `fixed_boxes`.

    Return (new_children, resume_at).

    """
    ...

def find_last_in_flow_child(children): # -> None:
    """Find and return the last in-flow child of given ``children``."""
    ...

def reversed_enumerate(seq): # -> zip[tuple[int, Any]]:
    """Like reversed(list(enumerate(seq))) without copying the whole seq."""
    ...

def remove_placeholders(context, box_list, absolute_boxes, fixed_boxes): # -> None:
    """Remove placeholders from absolute and fixed lists.

    For boxes that have been removed in find_earlier_page_break(), remove the
    matching placeholders in absolute_boxes and fixed_boxes.

    Also takes care of removed footnotes and floats.

    """
    ...

def avoid_page_break(page_break, context): # -> bool:
    """Test whether we should avoid breaks."""
    ...

def force_page_break(page_break, context): # -> bool:
    """Test whether we should force breaks."""
    ...

