"""
This type stub file was generated by pyright.
"""

"""Layout for columns."""
def columns_layout(context, box, bottom_space, skip_stack, containing_block, page_is_empty, absolute_boxes, fixed_boxes, adjoining_margins):
    """Lay out a multi-column ``box``."""
    ...

