"""
This type stub file was generated by pyright.
"""

"""Layout for flex containers and flex-items."""
class FlexLine(list):
    """Flex container line."""
    ...


def flex_layout(context, box, bottom_space, skip_stack, containing_block, page_is_empty, absolute_boxes, fixed_boxes, discard):
    ...

