"""
This type stub file was generated by pyright.
"""

from .min_max import handle_min_max_width

"""Layout for floating boxes."""
@handle_min_max_width
def float_width(box, context, containing_block): # -> None:
    ...

def float_layout(context, box, containing_block, absolute_boxes, fixed_boxes, bottom_space, skip_stack): # -> tuple[Any | BlockReplacedBox, Any | None]:
    """Set the width and position of floating ``box``."""
    ...

def find_float_position(context, box, containing_block):
    """Get the right position of the float ``box``."""
    ...

def get_clearance(context, box, collapsed_margin=...): # -> float | int | None:
    """Return None if there is no clearance, otherwise the clearance value."""
    ...

def avoid_collisions(context, box, containing_block, outer=...): # -> tuple[Literal[0], Literal[0], Any] | tuple[Any, Any, Any]:
    ...

