"""
This type stub file was generated by pyright.
"""

"""Layout for grid containers and grid-items."""
def grid_layout(context, box, bottom_space, skip_stack, containing_block, page_is_empty, absolute_boxes, fixed_boxes):
    ...

