"""
This type stub file was generated by pyright.
"""

"""Leaders management."""
def leader_index(box): # -> tuple[tuple[int, None], Any] | tuple[tuple[int, tuple[int, None] | tuple[int, tuple[int, None] | tuple[int, tuple[int, None] | tuple[int, tuple[int, None] | tuple[int, Any]]]]], Any | None] | tuple[None, None]:
    """Get the index of the first leader box in ``box``."""
    ...

def handle_leader(context, line, containing_block): # -> None:
    """Find a leader box in ``line`` and handle its text and its position."""
    ...

