"""
This type stub file was generated by pyright.
"""

"""Decorators handling min- and max- widths and heights."""
def handle_min_max_width(function): # -> _Wrapped[Callable[..., Any], Any, Callable[..., Any], Any]:
    """Decorate a function setting used width, handling {min,max}-width."""
    ...

def handle_min_max_height(function): # -> _Wrapped[Callable[..., Any], Any, Callable[..., Any], Any]:
    """Decorate a function setting used height, handling {min,max}-height."""
    ...

