"""
This type stub file was generated by pyright.
"""

"""Resolve percentages into fixed values."""
def percentage(value, refer_to): # -> Literal['auto']:
    """Return the percentage of the reference value, or the value unchanged.

    ``refer_to`` is the length for 100%. If ``refer_to`` is not a number, it
    just replaces percentages.

    """
    ...

def resolve_one_percentage(box, property_name, refer_to): # -> None:
    """Set a used length value from a computed length value.

    ``refer_to`` is the length for 100%. If ``refer_to`` is not a number, it
    just replaces percentages.

    """
    ...

def resolve_position_percentages(box, containing_block): # -> None:
    ...

def resolve_percentages(box, containing_block): # -> None:
    """Set used values as attributes of the box object."""
    ...

def resolve_radii_percentages(box): # -> None:
    ...

def adjust_box_sizing(box, axis): # -> None:
    ...

