"""
This type stub file was generated by pyright.
"""

"""Preferred and minimum preferred width.

Also known as max-content and min-content width, also known as the
shrink-to-fit algorithm.

Terms used (max-content width, min-content width) are defined in David
Baron's unofficial draft (https://dbaron.org/css/intrinsic/).

"""
def shrink_to_fit(context, box, available_content_width): # -> float | int:
    """Return the shrink-to-fit width of ``box``.

    *Warning:* both available_content_width and the return value are
    for width of the *content area*, not margin area.

    https://www.w3.org/TR/CSS21/visudet.html#float-width

    """
    ...

def min_content_width(context, box, outer=...): # -> float | int:
    """Return the min-content width for ``box``.

    This is the width by breaking at every line-break opportunity.

    """
    ...

def max_content_width(context, box, outer=...): # -> float | int:
    """Return the max-content width for ``box``.

    This is the width by only breaking at forced line breaks.

    """
    ...

def min_max(box, width): # -> float:
    """Get box width from given width and box min- and max-widths."""
    ...

def margin_width(box, width, left=..., right=...): # -> Literal[0]:
    """Add box paddings, borders and margins to ``width``."""
    ...

def adjust(box, outer, width, left=..., right=...): # -> float | Literal[0]:
    """Respect min/max and adjust width depending on ``outer``.

    If ``outer`` is set to ``True``, return margin width, else return content
    width.

    """
    ...

def block_min_content_width(context, box, outer=...): # -> float | Literal[0]:
    """Return the min-content width for a ``BlockBox``."""
    ...

def block_max_content_width(context, box, outer=...): # -> float | Literal[0]:
    """Return the max-content width for a ``BlockBox``."""
    ...

def inline_min_content_width(context, box, outer=..., skip_stack=..., first_line=..., is_line_start=...): # -> float | Literal[0]:
    """Return the min-content width for an ``InlineBox``.

    The width is calculated from the lines from ``skip_stack``. If
    ``first_line`` is ``True``, only the first line minimum width is
    calculated.

    """
    ...

def inline_max_content_width(context, box, outer=..., is_line_start=...): # -> float | Literal[0]:
    """Return the max-content width for an ``InlineBox``."""
    ...

def column_group_content_width(context, box): # -> float | Literal[0]:
    """Return the *-content width for a ``TableColumnGroupBox``."""
    ...

def table_cell_min_content_width(context, box, outer): # -> float | Literal[0]:
    """Return the min-content width for a ``TableCellBox``."""
    ...

def table_cell_min_max_content_width(context, box, outer=...): # -> tuple[Any | float | Literal[0], Any | float | int]:
    """Return the min- and max-content width for a ``TableCellBox``."""
    ...

def inline_line_widths(context, box, outer, is_line_start, minimum, skip_stack=..., first_line=...):
    """Yield line width for each line."""
    ...

def table_and_columns_preferred_widths(context, box, outer=...): # -> tuple[Any | float | int, Any | float | int, list[Any], list[Any], list[Any], list[Any], Any | Literal[0], list[Any]]:
    """Return content widths for the auto layout table and its columns.

    The tuple returned is
    ``(table_min_content_width, table_max_content_width,
       column_min_content_widths, column_max_content_widths,
       column_intrinsic_percentages, constrainedness,
       total_horizontal_border_spacing, grid)``

    https://dbaron.org/css/intrinsic/

    """
    ...

def replaced_min_content_width(box, outer=...): # -> float | Literal[0]:
    """Return the min-content width for an ``InlineReplacedBox``."""
    ...

def replaced_max_content_width(box, outer=...): # -> float | Literal[0]:
    """Return the max-content width for an ``InlineReplacedBox``."""
    ...

def flex_min_content_width(context, box, outer=...): # -> float | Literal[0]:
    """Return the min-content width for an ``FlexContainerBox``."""
    ...

def flex_max_content_width(context, box, outer=...): # -> float | Literal[0]:
    """Return the max-content width for an ``FlexContainerBox``."""
    ...

def trailing_whitespace_size(context, box): # -> Literal[0]:
    """Return the size of the trailing whitespace of ``box``."""
    ...

