"""
This type stub file was generated by pyright.
"""

from .min_max import handle_min_max_height, handle_min_max_width

"""Layout for images and other replaced elements.

See https://drafts.csswg.org/css-images-3/#sizing

"""
def default_image_sizing(intrinsic_width, intrinsic_height, intrinsic_ratio, specified_width, specified_height, default_width, default_height): # -> tuple[Any, Any]:
    """Default sizing algorithm for the concrete object size.

    Return a ``(concrete_width, concrete_height)`` tuple.

    See https://drafts.csswg.org/css-images-3/#default-sizing

    """
    ...

def contain_constraint_image_sizing(constraint_width, constraint_height, intrinsic_ratio): # -> tuple[Any, Any]:
    """Contain constraint sizing algorithm for the concrete object size.

    Return a ``(concrete_width, concrete_height)`` tuple.

    See https://drafts.csswg.org/css-images-3/#contain-constraint

    """
    ...

def cover_constraint_image_sizing(constraint_width, constraint_height, intrinsic_ratio): # -> tuple[Any, Any]:
    """Cover constraint sizing algorithm for the concrete object size.

    Return a ``(concrete_width, concrete_height)`` tuple.

    See https://drafts.csswg.org/css-images-3/#cover-constraint

    """
    ...

def replacedbox_layout(box): # -> tuple[Any, Any, Any, Any]:
    ...

@handle_min_max_width
def replaced_box_width(box, containing_block): # -> None:
    """Set the used width for replaced boxes."""
    ...

@handle_min_max_height
def replaced_box_height(box): # -> None:
    """Compute and set the used height for replaced boxes."""
    ...

def inline_replaced_box_layout(box, containing_block): # -> None:
    """Lay out an inline :class:`boxes.ReplacedBox` ``box``."""
    ...

def inline_replaced_box_width_height(box, containing_block): # -> None:
    ...

def min_max_auto_replaced(box): # -> None:
    """Resolve min/max constraints on replaced elements with 'auto' sizes."""
    ...

def block_replaced_box_layout(context, box, containing_block): # -> tuple[Any, None, dict[str, Any], list[Any], Literal[False]]:
    """Lay out the block :class:`boxes.ReplacedBox` ``box``."""
    ...

@handle_min_max_width
def block_replaced_width(box, containing_block): # -> None:
    ...

