"""
This type stub file was generated by pyright.
"""

"""Layout for tables and internal table boxes."""
def table_layout(context, table, bottom_space, skip_stack, containing_block, page_is_empty, absolute_boxes, fixed_boxes):
    """Layout for a table box."""
    ...

def add_top_padding(box, extra_padding): # -> None:
    """Increase the top padding of a box.

    This also translates the children.

    """
    ...

def fixed_table_layout(box): # -> None:
    """Run the fixed table layout and return a list of column widths.

    https://www.w3.org/TR/CSS21/tables.html#fixed-table-layout

    """
    ...

def auto_table_layout(context, box, containing_block): # -> None:
    """Run the auto table layout and return a list of column widths.

    https://www.w3.org/TR/CSS21/tables.html#auto-table-layout

    """
    ...

def table_wrapper_width(context, wrapper, containing_block): # -> None:
    """Find the width of each column and derive the wrapper width."""
    ...

def cell_baseline(cell):
    """Return the y position of a cell baseline from the top of its border box.

    See https://www.w3.org/TR/CSS21/tables.html#height-layout

    """
    ...

def find_in_flow_baseline(box, last=..., baseline_types=...): # -> None:
    """Return the absolute y position for the first (or last) in-flow baseline.

    If there’s no in-flow baseline, return None.

    """
    ...

def distribute_excess_width(context, grid, excess_width, column_widths, constrainedness, column_intrinsic_percentages, column_max_content_widths, column_slice=...): # -> None:
    """Distribute available width to columns.

    See https://www.w3.org/TR/css-tables-3/#distributing-width-to-columns

    """
    ...

TRANSPARENT = ...
def collapse_table_borders(table, grid_width, grid_height): # -> tuple[list[Any], list[Any]]:
    """Resolve border conflicts for a table in the collapsing border model.

    Take a :class:`TableBox`; set appropriate border widths on the table,
    column group, column, row group, row, and cell boxes; and return
    a data structure for the resolved collapsed border grid.

    """
    ...

