"""
This type stub file was generated by pyright.
"""

import re
from contextlib import suppress
from math import cos, hypot, pi, radians, sin, sqrt
from xml.etree import ElementTree
from cssselect2 import ElementWrapper
from ..urls import get_url_attribute
from .css import parse_declarations, parse_stylesheets
from .defs import apply_filters, clip_path, draw_gradient_or_pattern, paint_mask, use
from .images import image, svg
from .path import path
from .shapes import circle, ellipse, line, polygon, polyline, rect
from .text import text
from .bounding_box import EMPTY_BOUNDING_BOX, bounding_box, extend_bounding_box, is_valid_bounding_box
from .utils import PointError, alpha_value, color, normalize, parse_url, preserve_ratio, size, transform

"""Render SVG images."""
TAGS = ...
NOT_INHERITED_ATTRIBUTES = ...
COLOR_ATTRIBUTES = ...
DEF_TYPES = ...
class Node:
    """An SVG document node."""
    def __init__(self, wrapper, style) -> None:
        ...
    
    def copy(self): # -> Node:
        """Create a deep copy of the node as it was when first created."""
        ...
    
    def get(self, key, default=...):
        """Get attribute."""
        ...
    
    @property
    def tag(self):
        """XML tag name with no namespace."""
        ...
    
    @property
    def text(self):
        """XML node text."""
        ...
    
    @property
    def tail(self):
        """Text after the XML node."""
        ...
    
    @property
    def display(self):
        """Whether node should be displayed."""
        ...
    
    @property
    def visible(self):
        """Whether node is visible."""
        ...
    
    def cascade(self, child): # -> None:
        """Apply CSS cascade and other related operations to given child."""
        ...
    
    def __iter__(self): # -> Iterator[Any]:
        """Yield node children, handling cascade."""
        ...
    
    def get_viewbox(self): # -> tuple[float, ...] | None:
        """Get node viewBox as a tuple of floats."""
        ...
    
    def get_href(self, base_url): # -> str | None:
        """Get the href attribute, with or without a namespace."""
        ...
    
    def del_href(self): # -> None:
        """Remove the href attributes, with or without a namespace."""
        ...
    
    @staticmethod
    def process_whitespace(string, preserve): # -> str:
        """Replace newlines by spaces, and merge spaces if not preserved."""
        ...
    
    def get_child(self, id_): # -> None:
        """Get a child with given id in the whole child tree."""
        ...
    
    def text_children(self, element, trailing_space, text_root=...): # -> tuple[list[Any], Any]:
        """Handle text node by fixing whitespaces and flattening tails."""
        ...
    
    def flatten(self): # -> str:
        """Flatten text in node and in its children."""
        ...
    
    def pop_rotation(self, original_rotate, rotate): # -> None:
        """Merge nested letter rotations."""
        ...
    
    def override_iter(self, iterator): # -> None:
        """Override node’s children iterator."""
        ...
    
    def set_svg_size(self, svg, concrete_width, concrete_height): # -> None:
        """"Set SVG concrete and inner widths and heights from svg node."""
        ...
    


class SVG:
    """An SVG document."""
    def __init__(self, tree, url) -> None:
        ...
    
    def get_intrinsic_size(self, font_size): # -> tuple[float | Any | Literal[0] | None, float | Any | Literal[0] | None]:
        """Get intrinsic size of the image."""
        ...
    
    def get_viewbox(self): # -> tuple[float, ...] | None:
        """Get document viewBox as a tuple of floats."""
        ...
    
    def point(self, x, y, font_size): # -> tuple[float | Any | Literal[0], float | Any | Literal[0]]:
        """Compute size of an x/y or width/height couple."""
        ...
    
    def length(self, length, font_size): # -> float | Literal[0]:
        """Compute size of an arbirtary attribute."""
        ...
    
    def draw(self, stream, concrete_width, concrete_height, base_url, url_fetcher, context): # -> None:
        """Draw image on a stream."""
        ...
    
    def draw_node(self, node, font_size, fill_stroke=...):
        """Draw a node."""
        ...
    
    def draw_markers(self, node, font_size, fill_stroke): # -> None:
        """Draw markers defined in a node."""
        ...
    
    @staticmethod
    def get_paint(value): # -> tuple[None, None] | tuple[str | None, str | Any | None]:
        """Get paint fill or stroke attribute with a color or a URL."""
        ...
    
    def fill_stroke(self, node, font_size, text=...):
        """Paint fill and stroke for a node."""
        ...
    
    def transform(self, node, font_size): # -> None:
        """Apply a transformation string to the node."""
        ...
    
    def parse_defs(self, node): # -> None:
        """Parse defs included in a tree."""
        ...
    
    def inherit_defs(self): # -> None:
        """Handle inheritance of different defined elements lists."""
        ...
    
    def inherit_element(self, element, defs): # -> None:
        """Recursively handle inheritance of defined element."""
        ...
    
    def calculate_bounding_box(self, node, font_size, stroke=...): # -> tuple[float, float, Literal[0], Literal[0]] | tuple[Any, Any, Any, Any]:
        """Calculate the bounding box of a node."""
        ...
    


class Pattern(SVG):
    """SVG node applied as a pattern."""
    def __init__(self, tree, svg) -> None:
        ...
    
    def draw_node(self, node, font_size, fill_stroke=...): # -> None:
        ...
    


