"""
This type stub file was generated by pyright.
"""

"""Calculate bounding boxes of SVG tags."""
EMPTY_BOUNDING_BOX = ...
def bounding_box(svg, node, font_size, stroke): # -> tuple[float, float, Literal[0], Literal[0]] | tuple[Any, Any, Any, Any]:
    """Bounding box for any node."""
    ...

def bounding_box_rect(svg, node, font_size): # -> tuple[Any, Any, Any, Any]:
    """Bounding box for rect node."""
    ...

def bounding_box_circle(svg, node, font_size): # -> tuple[Any, Any, Any, Any]:
    """Bounding box for circle node."""
    ...

def bounding_box_ellipse(svg, node, font_size): # -> tuple[Any, Any, Any, Any]:
    """Bounding box for ellipse node."""
    ...

def bounding_box_line(svg, node, font_size): # -> tuple[Any, Any, Any, Any]:
    """Bounding box for line node."""
    ...

def bounding_box_polyline(svg, node, font_size): # -> tuple[Any, Any, Any, Any]:
    """Bounding box for polyline node."""
    ...

def bounding_box_path(svg, node, font_size): # -> tuple[float, float, Literal[0], Literal[0]] | tuple[Any, Any, Any, Any]:
    """Bounding box for path node."""
    ...

def bounding_box_text(svg, node, font_size): # -> Any | None:
    """Bounding box for text node."""
    ...

def bounding_box_g(svg, node, font_size): # -> tuple[float, float, Literal[0], Literal[0]] | tuple[Any, Any, Any, Any]:
    """Bounding box for g node."""
    ...

def bounding_box_use(svg, node, font_size): # -> tuple[float, float, Literal[0], Literal[0]] | tuple[Any, Any, Any | Literal[0], Any | Literal[0]]:
    """Bounding box for use node."""
    ...

def extend_bounding_box(bounding_box, points): # -> tuple[Any, Any, Any, Any]:
    """Extend a bounding box to include given points."""
    ...

def is_valid_bounding_box(bounding_box): # -> bool:
    """Check that a bounding box doesn’t have infinite boundaries."""
    ...

BOUNDING_BOX_METHODS = ...
