"""
This type stub file was generated by pyright.
"""

"""Apply CSS to SVG documents."""
def find_stylesheets_rules(tree, stylesheet_rules, url): # -> Generator[Any, Any, None]:
    """Find rules among stylesheet rules and imports."""
    ...

def parse_declarations(input): # -> tuple[list[Any], list[Any]]:
    """Parse declarations in a given rule content."""
    ...

def parse_stylesheets(tree, url): # -> tuple[Matcher, Matcher]:
    """Find stylesheets and return rule matchers in given tree."""
    ...

