"""
This type stub file was generated by pyright.
"""

"""Draw image and svg tags."""
def svg(svg, node, font_size): # -> None:
    """Draw svg tags."""
    ...

def image(svg, node, font_size): # -> None:
    """Draw image tags."""
    ...

