"""
This type stub file was generated by pyright.
"""

"""Draw simple shapes."""
def circle(svg, node, font_size): # -> None:
    """Draw circle tag."""
    ...

def ellipse(svg, node, font_size): # -> None:
    """Draw ellipse tag."""
    ...

def rect(svg, node, font_size): # -> None:
    """Draw rect tag."""
    ...

def line(svg, node, font_size): # -> None:
    """Draw line tag."""
    ...

def polygon(svg, node, font_size): # -> None:
    """Draw polygon tag."""
    ...

def polyline(svg, node, font_size): # -> None:
    """Draw polyline tag."""
    ...

