"""
This type stub file was generated by pyright.
"""

"""Draw text."""
class TextBox:
    """Dummy text box used to draw text."""
    def __init__(self, pango_layout, style) -> None:
        ...
    
    @property
    def text(self):
        ...
    


def text(svg, node, font_size):
    """Draw text node."""
    ...

