"""
This type stub file was generated by pyright.
"""

"""Util functions for SVG rendering."""
class PointError(Exception):
    """Exception raised when parsing a point fails."""
    ...


def normalize(string): # -> str:
    """Give a canonical version of a given value string."""
    ...

def size(string, font_size=..., percentage_reference=...): # -> float | Literal[0]:
    """Compute size from string, resolving units and percentages."""
    ...

def alpha_value(value): # -> float:
    """Return opacity between 0 and 1 from str, number or percentage."""
    ...

def point(svg, string, font_size): # -> tuple[*tuple[Any, ...], Any]:
    """Pop first two size values from a string."""
    ...

def preserve_ratio(svg, node, font_size, width, height, viewbox=...): # -> tuple[Literal[1], Literal[1], Literal[0], Literal[0]] | tuple[Any | int, Any | int, Any | Literal[0], Any | Literal[0]]:
    """Compute scale and translation needed to preserve ratio."""
    ...

def parse_url(url): # -> ParseResult:
    """Parse a URL, possibly in a "url(…)" string."""
    ...

def color(string): # -> Color | Literal['currentcolor'] | None:
    """Safely parse a color string and return a RGBA tuple."""
    ...

def transform(transform_string, transform_origin, font_size, normalized_diagonal): # -> Matrix:
    """Get a matrix corresponding to the transform string."""
    ...

