"""
This type stub file was generated by pyright.
"""

from typing import Optional
from flask import Flask
from pymongo import MongoClient
from ..base import ServerSideSession, ServerSideSessionInterface

class MongoDBSession(ServerSideSession):
    ...


class MongoDBSessionInterface(ServerSideSessionInterface):
    """A Session interface that uses mongodb as session storage. (`pymongo` required)

    :param client: A ``pymongo.MongoClient`` instance.
    :param key_prefix: A prefix that is added to all storage keys.
    :param use_signer: Whether to sign the session id cookie or not.
    :param permanent: Whether to use permanent session or not.
    :param sid_length: The length of the generated session id in bytes.
    :param serialization_format: The serialization format to use for the session data.
    :param db: The database to use.
    :param collection: The collection to use.

    .. versionadded:: 0.7
        The `serialization_format` and `app` parameters were added.

    .. versionadded:: 0.6
        The `sid_length` parameter was added.

    .. versionadded:: 0.2
        The `use_signer` parameter was added.
    """
    session_class = MongoDBSession
    ttl = ...
    def __init__(self, app: Flask, client: Optional[MongoClient] = ..., key_prefix: str = ..., use_signer: bool = ..., permanent: bool = ..., sid_length: int = ..., serialization_format: str = ..., db: str = ..., collection: str = ...) -> None:
        ...
    


