"""
This type stub file was generated by pyright.
"""

from typing import Optional
from flask import Flask
from redis import Redis
from ..base import ServerSideSession, ServerSideSessionInterface

class RedisSession(ServerSideSession):
    ...


class RedisSessionInterface(ServerSideSessionInterface):
    """Uses the Redis key-value store as a session storage. (`redis-py` required)

    :param client: A ``redis.Redis`` instance.
    :param key_prefix: A prefix that is added to all storage keys.
    :param use_signer: Whether to sign the session id cookie or not.
    :param permanent: Whether to use permanent session or not.
    :param sid_length: The length of the generated session id in bytes.
    :param serialization_format: The serialization format to use for the session data.

    .. versionadded:: 0.7
        The `serialization_format` and `app` parameters were added.

    .. versionadded:: 0.6
        The `sid_length` parameter was added.

    .. versionadded:: 0.2
        The `use_signer` parameter was added.
    """
    session_class = RedisSession
    ttl = ...
    def __init__(self, app: Flask, client: Optional[Redis] = ..., key_prefix: str = ..., use_signer: bool = ..., permanent: bool = ..., sid_length: int = ..., serialization_format: str = ...) -> None:   # type: ignore
        ...
    


